--- 
title: "R-anvisningar till *Grundläggande statistik*"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
editor_options: 
  chunk_output_type: console
---

# Introduktion {-}

Detta dokument ger en introduktion till R för en kurs i grundläggande statistik.

```{r, echo = F}
knitr::opts_chunk$set(eval = T, message = F, warning = F, error = F, fig.height = 3.5, fig.align = "center")
```

```{r, echo = F}
rm(list = ls())
library(tidyverse)
select <- dplyr::select
```

```{r, echo = F}
library(knitr)
library(kableExtra)

kable <- function(x, digits = 4){
  x %>% 
    kbl(booktabs = T, digits = digits) %>% 
    kable_styling(full_width = F)
}
```

```{r, echo = F}
theme_col <- "white"
theme_set(theme_bw() + 
            theme(plot.background = element_rect(fill = theme_col, color = theme_col),
                  text = element_text(family = "serif"),
                  legend.background = element_rect(fill = theme_col, color = theme_col),
                  legend.key = element_rect(fill = theme_col, color = theme_col)))
```
