<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>3 Ett stickprov av normalfördelad data | R-anvisningar till Grundläggande statistik</title>
  <meta name="description" content="3 Ett stickprov av normalfördelad data | R-anvisningar till Grundläggande statistik" />
  <meta name="generator" content="bookdown 0.44 and GitBook 2.6.7" />

  <meta property="og:title" content="3 Ett stickprov av normalfördelad data | R-anvisningar till Grundläggande statistik" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="3 Ett stickprov av normalfördelad data | R-anvisningar till Grundläggande statistik" />
  
  
  



<meta name="date" content="2025-09-19" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="beskrivande-statistik.html"/>
<link rel="next" href="variansanalys.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">R-anvisningar</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introduktion</a></li>
<li class="chapter" data-level="" data-path="installation-av-r-och-rstudio.html"><a href="installation-av-r-och-rstudio.html"><i class="fa fa-check"></i>Installation av R och RStudio</a>
<ul>
<li class="chapter" data-level="0.1" data-path="installation-av-r-och-rstudio.html"><a href="installation-av-r-och-rstudio.html#inledning"><i class="fa fa-check"></i><b>0.1</b> Inledning</a></li>
<li class="chapter" data-level="0.2" data-path="installation-av-r-och-rstudio.html"><a href="installation-av-r-och-rstudio.html#installation-av-r"><i class="fa fa-check"></i><b>0.2</b> Installation av R</a></li>
<li class="chapter" data-level="0.3" data-path="installation-av-r-och-rstudio.html"><a href="installation-av-r-och-rstudio.html#installation-av-rstudio"><i class="fa fa-check"></i><b>0.3</b> Installation av RStudio</a></li>
<li class="chapter" data-level="0.4" data-path="Rmd/Datorövning-3.html"><a href="#gr%C3%A4nssnittet-i-rstudio"><i class="fa fa-check"></i><b>0.4</b> Gränssnittet i RStudio</a></li>
<li class="chapter" data-level="0.5" data-path="installation-av-r-och-rstudio.html"><a href="installation-av-r-och-rstudio.html#paket-i-r"><i class="fa fa-check"></i><b>0.5</b> Paket i R</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="datahantering-och-grafer.html"><a href="datahantering-och-grafer.html"><i class="fa fa-check"></i><b>1</b> Datahantering och grafer</a>
<ul>
<li class="chapter" data-level="1.1" data-path="datahantering-och-grafer.html"><a href="datahantering-och-grafer.html#uppstart-och-orientering"><i class="fa fa-check"></i><b>1.1</b> Uppstart och orientering</a></li>
<li class="chapter" data-level="1.2" data-path="Rmd/Datorövning-3.html"><a href="#packages-fr%C3%A5n-cran"><i class="fa fa-check"></i><b>1.2</b> <em>Packages</em> från CRAN</a></li>
<li class="chapter" data-level="1.3" data-path="datahantering-och-grafer.html"><a href="datahantering-och-grafer.html#objekt-och-funktioner"><i class="fa fa-check"></i><b>1.3</b> Objekt och funktioner</a></li>
<li class="chapter" data-level="1.4" data-path="datahantering-och-grafer.html"><a href="datahantering-och-grafer.html#sekvenser-av-funktioner"><i class="fa fa-check"></i><b>1.4</b> Sekvenser av funktioner</a></li>
<li class="chapter" data-level="1.5" data-path="datahantering-och-grafer.html"><a href="datahantering-och-grafer.html#datainskrivning"><i class="fa fa-check"></i><b>1.5</b> Datainskrivning</a></li>
<li class="chapter" data-level="1.6" data-path="datahantering-och-grafer.html"><a href="datahantering-och-grafer.html#urval-ur-en-tabell-med-select-och-filter"><i class="fa fa-check"></i><b>1.6</b> Urval ur en tabell med <code>select</code> och <code>filter</code></a></li>
<li class="chapter" data-level="1.7" data-path="datahantering-och-grafer.html"><a href="datahantering-och-grafer.html#grafer-med-ggplot2"><i class="fa fa-check"></i><b>1.7</b> Grafer med <code>ggplot2</code></a></li>
<li class="chapter" data-level="1.8" data-path="datahantering-och-grafer.html"><a href="datahantering-och-grafer.html#ai-uppgift-i"><i class="fa fa-check"></i><b>1.8</b> AI-uppgift I</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="beskrivande-statistik.html"><a href="beskrivande-statistik.html"><i class="fa fa-check"></i><b>2</b> Beskrivande statistik</a>
<ul>
<li class="chapter" data-level="2.1" data-path="Rmd/Datorövning-3.html"><a href="#repetition-fr%C3%A5n-dator%C3%B6vning-1"><i class="fa fa-check"></i><b>2.1</b> Repetition från datorövning 1</a></li>
<li class="chapter" data-level="2.2" data-path="Rmd/Datorövning-3.html"><a href="#import-av-data-fr%C3%A5n-en-excelfil"><i class="fa fa-check"></i><b>2.2</b> Import av data från en Excelfil</a></li>
<li class="chapter" data-level="2.3" data-path="Rmd/Datorövning-3.html"><a href="#%C3%A4ndra-och-skapa-nya-kolumner-med-mutate"><i class="fa fa-check"></i><b>2.3</b> Ändra och skapa nya kolumner med <code>mutate</code></a></li>
<li class="chapter" data-level="2.4" data-path="Rmd/Datorövning-3.html"><a href="#sammanfattande-l%C3%A4gesm%C3%A5tt"><i class="fa fa-check"></i><b>2.4</b> Sammanfattande lägesmått</a></li>
<li class="chapter" data-level="2.5" data-path="Rmd/Datorövning-3.html"><a href="#sammanfattande-spridningsm%C3%A5tt"><i class="fa fa-check"></i><b>2.5</b> Sammanfattande spridningsmått</a></li>
<li class="chapter" data-level="2.6" data-path="beskrivande-statistik.html"><a href="beskrivande-statistik.html#ordna-upp-beskrivande-statistik-och-exportera"><i class="fa fa-check"></i><b>2.6</b> Ordna upp beskrivande statistik och exportera</a></li>
<li class="chapter" data-level="2.7" data-path="Rmd/Datorövning-3.html"><a href="#kumulativt-medelv%C3%A4rde"><i class="fa fa-check"></i><b>2.7</b> Kumulativt medelvärde</a></li>
<li class="chapter" data-level="2.8" data-path="beskrivande-statistik.html"><a href="beskrivande-statistik.html#tredimensionella-grafer-med-plotly"><i class="fa fa-check"></i><b>2.8</b> Tredimensionella grafer med <code>plotly</code></a></li>
<li class="chapter" data-level="2.9" data-path="beskrivande-statistik.html"><a href="beskrivande-statistik.html#ai-uppgift-ii"><i class="fa fa-check"></i><b>2.9</b> AI-uppgift II</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="Rmd/Datorövning-3.html"><a href="#ett-stickprov-av-normalf%C3%B6rdelad-data"><i class="fa fa-check"></i><b>3</b> Ett stickprov av normalfördelad data</a>
<ul>
<li class="chapter" data-level="3.1" data-path="Rmd/Datorövning-3.html"><a href="#repetition-fr%C3%A5n-dator%C3%B6vning-2"><i class="fa fa-check"></i><b>3.1</b> Repetition från datorövning 2</a></li>
<li class="chapter" data-level="3.2" data-path="Rmd/Datorövning-3.html"><a href="#test-av-medelv%C3%A4rde-f%C3%B6r-normalf%C3%B6rdelad-data"><i class="fa fa-check"></i><b>3.2</b> Test av medelvärde för normalfördelad data</a></li>
<li class="chapter" data-level="3.3" data-path="Rmd/Datorövning-3.html"><a href="#konfidensintervall-f%C3%B6r-normalf%C3%B6rdelad-data"><i class="fa fa-check"></i><b>3.3</b> Konfidensintervall för normalfördelad data</a></li>
<li class="chapter" data-level="3.4" data-path="Rmd/Datorövning-3.html"><a href="#normalf%C3%B6rdelad-data"><i class="fa fa-check"></i><b>3.4</b> Normalfördelad data</a></li>
<li class="chapter" data-level="3.5" data-path="Rmd/Datorövning-3.html"><a href="#centrala-gr%C3%A4nsv%C3%A4rdesatsen"><i class="fa fa-check"></i><b>3.5</b> Centrala gränsvärdesatsen</a></li>
<li class="chapter" data-level="3.6" data-path="ett-stickprov-av-normalfördelad-data.html"><a href="ett-stickprov-av-normalfördelad-data.html"><i class="fa fa-check"></i><b>3.6</b> AI-uppgift III</a></li>
<li class="chapter" data-level="3.7" data-path="Rmd/Datorövning-3.html"><a href="#bonus.-simuleringar-f%C3%B6r-t-test"><i class="fa fa-check"></i><b>3.7</b> Bonus. Simuleringar för t-test</a></li>
<li class="chapter" data-level="3.8" data-path="Rmd/Datorövning-3.html"><a href="#ett-stickprov-av-icke-normalf%C3%B6rdelad-data"><i class="fa fa-check"></i><b>3.8</b> Ett stickprov av icke-normalfördelad data</a></li>
<li class="chapter" data-level="3.9" data-path="Rmd/Datorövning-3.html"><a href="#repetition-av-dator%C3%B6vning-3"><i class="fa fa-check"></i><b>3.9</b> Repetition av datorövning 3</a></li>
<li class="chapter" data-level="3.10" data-path="Rmd/Datorövning-3.html"><a href="#proportioner-fr%C3%A5n-bin%C3%A4r-data"><i class="fa fa-check"></i><b>3.10</b> Proportioner från binär data</a></li>
<li class="chapter" data-level="3.11" data-path="Rmd/Datorövning-3.html"><a href="#konfidensintervall-f%C3%B6r-proportioner"><i class="fa fa-check"></i><b>3.11</b> Konfidensintervall för proportioner</a></li>
<li class="chapter" data-level="3.12" data-path="Rmd/Datorövning-3.html"><a href="#chi-tv%C3%A5-test-f%C3%B6r-goodness-of-fit"><i class="fa fa-check"></i><b>3.12</b> Chi-två-test för goodness-of-fit</a></li>
<li class="chapter" data-level="3.13" data-path="ett-stickprov-av-normalfördelad-data.html"><a href="ett-stickprov-av-normalfördelad-data.html#bonus.-interaktiva-kartor-med-leaflet"><i class="fa fa-check"></i><b>3.13</b> Bonus. Interaktiva kartor med leaflet</a></li>
<li class="chapter" data-level="3.14" data-path="Rmd/Datorövning-3.html"><a href="#test-f%C3%B6r-tv%C3%A5-stickprov"><i class="fa fa-check"></i><b>3.14</b> Test för två stickprov</a></li>
<li class="chapter" data-level="3.15" data-path="Rmd/Datorövning-3.html"><a href="#repetition-av-dator%C3%B6vning-4"><i class="fa fa-check"></i><b>3.15</b> Repetition av datorövning 4</a></li>
<li class="chapter" data-level="3.16" data-path="Rmd/Datorövning-3.html"><a href="#tv%C3%A5-stickprov-och-normalf%C3%B6rdelad-data"><i class="fa fa-check"></i><b>3.16</b> Två stickprov och normalfördelad data</a>
<ul>
<li class="chapter" data-level="3.16.1" data-path="Rmd/Datorövning-3.html"><a href="#t-test-f%C3%B6r-tv%C3%A5-matchade-stickprov"><i class="fa fa-check"></i><b>3.16.1</b> t-test för två matchade stickprov</a></li>
<li class="chapter" data-level="3.16.2" data-path="Rmd/Datorövning-3.html"><a href="#t-test-f%C3%B6r-tv%C3%A5-oberoende-stickprov"><i class="fa fa-check"></i><b>3.16.2</b> t-test för två oberoende stickprov</a></li>
</ul></li>
<li class="chapter" data-level="3.17" data-path="Rmd/Datorövning-3.html"><a href="#z-test-och-konfidensintervall-f%C3%B6r-tv%C3%A5-proportioner"><i class="fa fa-check"></i><b>3.17</b> z-test och konfidensintervall för två proportioner</a></li>
<li class="chapter" data-level="3.18" data-path="Rmd/Datorövning-3.html"><a href="#chi-tv%C3%A5-test-f%C3%B6r-korstabeller"><i class="fa fa-check"></i><b>3.18</b> Chi-två-test för korstabeller</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="variansanalys.html"><a href="variansanalys.html"><i class="fa fa-check"></i><b>4</b> Variansanalys</a>
<ul>
<li class="chapter" data-level="4.1" data-path="Rmd/Datorövning-3.html"><a href="#repetition-av-dator%C3%B6vning-5"><i class="fa fa-check"></i><b>4.1</b> Repetition av datorövning 5</a></li>
<li class="chapter" data-level="4.2" data-path="Rmd/Datorövning-3.html"><a href="#allm%C3%A4nt"><i class="fa fa-check"></i><b>4.2</b> Allmänt</a></li>
<li class="chapter" data-level="4.3" data-path="variansanalys.html"><a href="variansanalys.html#variansanalys.-en-faktor"><i class="fa fa-check"></i><b>4.3</b> Variansanalys. En faktor</a></li>
<li class="chapter" data-level="4.4" data-path="variansanalys.html"><a href="variansanalys.html#variansanalys.-en-faktor-med-block"><i class="fa fa-check"></i><b>4.4</b> Variansanalys. En faktor med block</a></li>
<li class="chapter" data-level="4.5" data-path="Rmd/Datorövning-3.html"><a href="#bonus.-tv%C3%A5-faktorer-med-block"><i class="fa fa-check"></i><b>4.5</b> Bonus. Två faktorer med block</a></li>
<li class="chapter" data-level="4.6" data-path="variansanalys.html"><a href="variansanalys.html#regression-och-korrelation"><i class="fa fa-check"></i><b>4.6</b> Regression och korrelation</a></li>
<li class="chapter" data-level="4.7" data-path="Rmd/Datorövning-3.html"><a href="#repetition-av-dator%C3%B6vning-6"><i class="fa fa-check"></i><b>4.7</b> Repetition av datorövning 6</a></li>
<li class="chapter" data-level="4.8" data-path="variansanalys.html"><a href="variansanalys.html#regression"><i class="fa fa-check"></i><b>4.8</b> Regression</a></li>
<li class="chapter" data-level="4.9" data-path="variansanalys.html"><a href="variansanalys.html#korrelation"><i class="fa fa-check"></i><b>4.9</b> Korrelation</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">R-anvisningar till <em>Grundläggande statistik</em></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="ett-stickprov-av-normalfördelad-data" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">3</span> Ett stickprov av normalfördelad data<a href="#ett-stickprov-av-normalf%C3%B6rdelad-data" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Datorövning 3 handlar om hypotestest och konfidensintervall för ett stickprov av normalfördelad data. Efter övningen ska vi kunna</p>
<ul>
<li>genomföra och tolka ett t-test för normalfördelad data,</li>
<li>beräkna och tolka ett konfidensintervall för normalfördelad data,</li>
<li>använda simulerad data för att förstå t-testets egenskaper.</li>
</ul>
<div id="repetition-från-datorövning-2" class="section level2 hasAnchor" number="3.1">
<h2><span class="header-section-number">3.1</span> Repetition från datorövning 2<a href="#repetition-fr%C3%A5n-dator%C3%B6vning-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>När man startar en ny R-session bör man ladda de paket man vet kommer behövas med <code>library()</code>. Om paket inte finns installerade måste man först köra <code>install.packages()</code>.</p>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb103-1" tabindex="-1"></a><span class="co"># install.packages(&quot;tidyverse&quot;)</span></span>
<span id="cb103-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb103-2" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
<p>I datorövning 2 tittade vi på hur insamlade variabler kan sammanfattas med lägesmått och spridningsmått. Ett enkelt sätt att ta fram dem är att använda <code>summarise()</code> och ange de mått och variabler man vill använda. Vi hade uppe ett exempel på data från Gapminder som vi importerade från en excel-fil. För nu kan vi dock hämta datan från paketet <code>gapminder</code>.</p>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb104-1" tabindex="-1"></a><span class="co"># install.packages(&quot;gapminder&quot;)</span></span>
<span id="cb104-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb104-2" tabindex="-1"></a><span class="fu">library</span>(gapminder)</span>
<span id="cb104-3"><a href="ett-stickprov-av-normalfördelad-data.html#cb104-3" tabindex="-1"></a></span>
<span id="cb104-4"><a href="ett-stickprov-av-normalfördelad-data.html#cb104-4" tabindex="-1"></a>gapminder <span class="sc">%&gt;%</span> </span>
<span id="cb104-5"><a href="ett-stickprov-av-normalfördelad-data.html#cb104-5" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">2007</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb104-6"><a href="ett-stickprov-av-normalfördelad-data.html#cb104-6" tabindex="-1"></a>  <span class="fu">group_by</span>(continent) <span class="sc">%&gt;%</span> </span>
<span id="cb104-7"><a href="ett-stickprov-av-normalfördelad-data.html#cb104-7" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="st">`</span><span class="at">Livslängd, medel</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">mean</span>(lifeExp),</span>
<span id="cb104-8"><a href="ett-stickprov-av-normalfördelad-data.html#cb104-8" tabindex="-1"></a>            <span class="st">`</span><span class="at">Befolkning, median</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">median</span>(pop),</span>
<span id="cb104-9"><a href="ett-stickprov-av-normalfördelad-data.html#cb104-9" tabindex="-1"></a>            <span class="st">`</span><span class="at">Bnp per capita, standardavvikelse</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">sd</span>(gdpPercap))</span></code></pre></div>
<p>Beskrivande mått sammanfattas ofta i någon enkel vetenskaplig graf. Två vanliga val är lådagrammet, som illustrerar kvartiler och möjliga extremvärden, och stapeldiagrammet med felstaplar. Vi ger först ett exempel på ett lådagram över livslängd per kontinent uppdelat efter år.</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb105-1" tabindex="-1"></a><span class="fu">ggplot</span>(gapminder, <span class="fu">aes</span>(lifeExp, continent, <span class="at">fill =</span> continent)) <span class="sc">+</span></span>
<span id="cb105-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb105-2" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb105-3"><a href="ett-stickprov-av-normalfördelad-data.html#cb105-3" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> year)</span></code></pre></div>
<p>Därefter ett exempel på ett stapeldiagram med felstaplar för samma data. Felstapeln ges av standardavvikelsen.</p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb106-1" tabindex="-1"></a>dat_sum <span class="ot">&lt;-</span> gapminder <span class="sc">%&gt;%</span> </span>
<span id="cb106-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb106-2" tabindex="-1"></a>  <span class="fu">group_by</span>(continent, year) <span class="sc">%&gt;%</span> </span>
<span id="cb106-3"><a href="ett-stickprov-av-normalfördelad-data.html#cb106-3" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Mean =</span> <span class="fu">mean</span>(lifeExp),</span>
<span id="cb106-4"><a href="ett-stickprov-av-normalfördelad-data.html#cb106-4" tabindex="-1"></a>            <span class="at">SD =</span> <span class="fu">sd</span>(lifeExp))</span>
<span id="cb106-5"><a href="ett-stickprov-av-normalfördelad-data.html#cb106-5" tabindex="-1"></a>dat_sum</span>
<span id="cb106-6"><a href="ett-stickprov-av-normalfördelad-data.html#cb106-6" tabindex="-1"></a></span>
<span id="cb106-7"><a href="ett-stickprov-av-normalfördelad-data.html#cb106-7" tabindex="-1"></a><span class="fu">ggplot</span>(dat_sum, <span class="fu">aes</span>(continent, Mean, <span class="at">fill =</span> continent)) <span class="sc">+</span></span>
<span id="cb106-8"><a href="ett-stickprov-av-normalfördelad-data.html#cb106-8" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb106-9"><a href="ett-stickprov-av-normalfördelad-data.html#cb106-9" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> Mean <span class="sc">-</span> SD, <span class="at">ymax =</span> Mean <span class="sc">+</span> SD), </span>
<span id="cb106-10"><a href="ett-stickprov-av-normalfördelad-data.html#cb106-10" tabindex="-1"></a>                <span class="at">width =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb106-11"><a href="ett-stickprov-av-normalfördelad-data.html#cb106-11" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> year)</span></code></pre></div>
</div>
<div id="test-av-medelvärde-för-normalfördelad-data" class="section level2 hasAnchor" number="3.2">
<h2><span class="header-section-number">3.2</span> Test av medelvärde för normalfördelad data<a href="#test-av-medelv%C3%A4rde-f%C3%B6r-normalf%C3%B6rdelad-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Om man har en normalfördelad variabel och vill testa om populationens medelvärde är skilt från något hypotetiskt värde <span class="math inline">\(\mu_0\)</span> kan man använda ett <em>t-test för ett stickprov</em>. Ta som exempel följande data på 8 observationer av havreskörd. Av någon historisk anledning vill man testa om populationsmedelvärdet är skilt från 50.</p>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb107-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb107-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb107-2" tabindex="-1"></a></span>
<span id="cb107-3"><a href="ett-stickprov-av-normalfördelad-data.html#cb107-3" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">y =</span> <span class="fu">c</span>(<span class="fl">49.8</span>, <span class="fl">58.4</span>, <span class="fl">49.4</span>, <span class="fl">57.1</span>, </span>
<span id="cb107-4"><a href="ett-stickprov-av-normalfördelad-data.html#cb107-4" tabindex="-1"></a>                        <span class="fl">52.2</span>, <span class="fl">49.1</span>, <span class="fl">44.6</span>, <span class="fl">55.4</span>))</span>
<span id="cb107-5"><a href="ett-stickprov-av-normalfördelad-data.html#cb107-5" tabindex="-1"></a>dat</span>
<span id="cb107-6"><a href="ett-stickprov-av-normalfördelad-data.html#cb107-6" tabindex="-1"></a></span>
<span id="cb107-7"><a href="ett-stickprov-av-normalfördelad-data.html#cb107-7" tabindex="-1"></a><span class="fu">ggplot</span>(dat, <span class="fu">aes</span>(y, <span class="dv">0</span>)) <span class="sc">+</span> </span>
<span id="cb107-8"><a href="ett-stickprov-av-normalfördelad-data.html#cb107-8" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb107-9"><a href="ett-stickprov-av-normalfördelad-data.html#cb107-9" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">50</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p>I grafen ser vi att värdena ligger jämt spridda kring 50, så 50 är nog ganska rimligt som medelvärde, men låt oss göra ett formellt test.
I R kan ett t-test genomföras med <code>t.test()</code>.</p>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb108-1" tabindex="-1"></a><span class="fu">t.test</span>(dat<span class="sc">$</span>y, <span class="at">mu =</span> <span class="dv">50</span>)   <span class="co"># Ett t-test på variabeln y</span></span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  dat$y
## t = 1.2086, df = 7, p-value = 0.266
## alternative hypothesis: true mean is not equal to 50
## 95 percent confidence interval:
##  48.08713 55.91287
## sample estimates:
## mean of x 
##        52</code></pre>
<p>Utskriften ger ett p-värde från vilket vi kan dra en slutsats. I det här fallet är p-värdet högt (över fem procent) så vi kan inte förkasta nollhypotesen (vilken är att populationsmedelvärdet är lika med 50).</p>
<p>Vi tittar nu på stegen bakom t-testet.
Ett t-test bygger, som alla hypotestest, på en serie steg:</p>
<ol style="list-style-type: decimal">
<li>sätt upp en <em>nollhypotes</em> och en <em>alternativhypotes</em>,</li>
<li>beräkna ett <em>testvärde</em> från en testfunktion,</li>
<li>identifiera en <em>testfördelning</em>,</li>
<li>beräkna ett <em>p-värde</em>, eller uppskatta ett genom att ställa testvärde mot ett kritiskt värde,</li>
<li>dra en klar <em>slutsats</em> om statistisk signifikans.</li>
</ol>
<p>Vi vill testa om medelskörden är skild från 50, så hypoteser ges av</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu\)</span> lika med 50</li>
<li><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\mu\)</span> ej lika med 50</li>
</ul>
<p>Alternativhypotesen är tvåsidig - vi tittar både på möjligheten att populationsmedelvärdet är större och på möjligheten att det är mindre.</p>
<div class="exercise">
<p><span id="exr:unlabeled-div-43" class="exercise"><strong>Uppgift 3.1  (Ensidig mothypotes) </strong></span>Hur hade hypoteserna sett ut om vi ville testa om medelvärdet är <em>större</em> än 50?</p>
</div>
<p>Från datan har vi åtta observation och vi kan ta fram stickprovsmedelvärde och standardavvikelse i R.</p>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb110-1" tabindex="-1"></a><span class="fu">mean</span>(dat<span class="sc">$</span>y)</span></code></pre></div>
<pre><code>## [1] 52</code></pre>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb112-1" tabindex="-1"></a><span class="fu">sd</span>(dat<span class="sc">$</span>y)</span></code></pre></div>
<pre><code>## [1] 4.680354</code></pre>
<p>Vårt mål är att testa ett medelvärde och det är rimligt att anta normalfördelning för den undersökta variabeln. Det lämpliga testet är då ett t-test för ett stickprov och testvärdet kan beräknas av en testfunktion som ges av det observerade stickprovet minus nollhypotesens värde, delat på standardavvikelsen delat på roten ur antalet observationer.</p>
<p><span class="math display">\[t = \frac{\bar{y} - \mu_0}{s/\sqrt{n}}\]</span></p>
<div class="exercise">
<p><span id="exr:unlabeled-div-44" class="exercise"><strong>Uppgift 3.2  (Handräkning) </strong></span>Beräkna t-värdet på miniräknare eller telefon. Finns det beräknade t-värdet i utskriften från <code>t.test()</code>?</p>
</div>
<p>Nästa steg är att identifiera testfördelning, det vill säga den slumpfördelning testvärdet följet om nollhypotesen är sann. I det här fallet är testfördelningen en t-fördelning med n - 1 frihetsgrader. Vi har åtta observationer, så antalet frihetsgrader blir 7. I R kan man ta fram täthetsfunktionen för en t-fördelning med <code>dt()</code> och fördelningsfunktionen med <code>pt()</code>. Kurvorna kan plottas med <code>geom_function()</code> i en ggplot.</p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb114-1" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb114-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb114-2" tabindex="-1"></a>  <span class="fu">geom_function</span>(<span class="at">fun =</span> dt, <span class="at">args =</span> <span class="fu">list</span>(<span class="at">df =</span> <span class="dv">7</span>)) <span class="sc">+</span></span>
<span id="cb114-3"><a href="ett-stickprov-av-normalfördelad-data.html#cb114-3" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="sc">-</span><span class="dv">5</span>,<span class="dv">5</span>)</span></code></pre></div>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb115-1" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb115-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb115-2" tabindex="-1"></a>  <span class="fu">geom_function</span>(<span class="at">fun =</span> pt, <span class="at">args =</span> <span class="fu">list</span>(<span class="at">df =</span> <span class="dv">7</span>)) <span class="sc">+</span></span>
<span id="cb115-3"><a href="ett-stickprov-av-normalfördelad-data.html#cb115-3" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="sc">-</span><span class="dv">5</span>,<span class="dv">5</span>)</span></code></pre></div>
<p>Från testfördelningen kan vi nu ta fram ett p-värde. P-värdet kan illustreras som ytan under t-fördelning <em>bortom</em> test-värdet. I ett tvåsidigt test tar vi med bägge svansarna.</p>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb116-1" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb116-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb116-2" tabindex="-1"></a>  <span class="fu">geom_function</span>(<span class="at">fun =</span> dt, <span class="at">args =</span> <span class="fu">list</span>(<span class="at">df =</span> <span class="dv">7</span>)) <span class="sc">+</span></span>
<span id="cb116-3"><a href="ett-stickprov-av-normalfördelad-data.html#cb116-3" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">1.2086</span>, <span class="fl">1.2086</span>), </span>
<span id="cb116-4"><a href="ett-stickprov-av-normalfördelad-data.html#cb116-4" tabindex="-1"></a>             <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb116-5"><a href="ett-stickprov-av-normalfördelad-data.html#cb116-5" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="sc">-</span><span class="dv">5</span>,<span class="dv">5</span>)</span></code></pre></div>
<p>Ytorna i <em>svansarna</em> motsvarar p-värdet. De anger sannolikheten att få ett större t-värde än det vi fått, under antagandet att nollhypotesen stämmer. Det exakta p-värdet gavs av <code>t.test()</code>-funktionen som 0.266. En tolkning av det är om försöket upprepas ett stort antal gånger och nollhypotesen är sann, kommer vi 26.6 procent av gångerna få ett större testvärde än 1.2086. Det vi observerar är ganska sannolikt om nollhypotesen stämmer, vilket tyder på att nollhypotesen är rimlig.</p>
<p>Det avslutande steget är att dra en formell slutsats och ge ett tydligt svar. Det beräknade p-värdet ställs mot en förbestämd signifikansnivå, oftast fem procent. Här är p-värdet över den nivån, så vi kan inte förkasta nollhyptesen. Slutsatsen är att det <em>inte</em> finns någon signifikant skillnad från 50 i havreskörd.</p>
<div class="exercise">
<p><span id="exr:unlabeled-div-45" class="exercise"><strong>Uppgift 3.3  (Kritiskt värde) </strong></span>Om man gör ett t-test för hand kan man inte enkelt ta fram ett p-värde, men kan se om p-värdet är större eller mindre än fem procent genom att ställa testvärdet mot ett kritiskt värde. Använd en tabell för t-fördelning för att hitta det kritiska värdet.</p>
<p>I R kan man ta fram kritiska värden med <code>qt()</code>. För fem procent i svansarna har man 0.025 i respektive svans och det kritiska värdet ges av</p>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb117-1" tabindex="-1"></a><span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="dv">7</span>)</span></code></pre></div>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-46" class="exercise"><strong>Uppgift 3.4  (Ensidigt test) </strong></span>Använd <code>?t.test</code> för att ta fram funktionens hjälpsida. Försök att utifrån hjälpsidan beräkna ett <em>ensidigt</em> test för att se om medelskörden är <em>större</em> än 50.</p>
</div>
</div>
<div id="konfidensintervall-för-normalfördelad-data" class="section level2 hasAnchor" number="3.3">
<h2><span class="header-section-number">3.3</span> Konfidensintervall för normalfördelad data<a href="#konfidensintervall-f%C3%B6r-normalf%C3%B6rdelad-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Utfallet av ett t-test beror på nollhypotesen värde, så om vi ändrar det kommer vi få ett annat p-värde.</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb118-1" tabindex="-1"></a><span class="fu">t.test</span>(dat<span class="sc">$</span>y, <span class="at">mu =</span> <span class="dv">50</span>)</span>
<span id="cb118-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb118-2" tabindex="-1"></a><span class="fu">t.test</span>(dat<span class="sc">$</span>y, <span class="at">mu =</span> <span class="dv">48</span>)</span></code></pre></div>
<p>Från p-värdena kan man dra slutsatsen att förkasta vid nollhypotesen att <span class="math inline">\(\mu\)</span> är 48, men inte förkasta vid nollhypotesen att mu är 50. Värdet 50 är alltså i någon mening ett mer troligt värde på populationens medelvärde än vad 48 är. <em>Konfidensintervall</em> kan ses som en generalisering av den tanken: ett konfidensintervall ger ett spann av värden där man <em>inte</em> förkastar. Intervallet tolkas vanligen som att det täcker det sanna populationsmedelvärdet med en viss konfidens.</p>
<p>För ett stickprov och antagen normalfördelning ges konfidensintervallet (med konfidensgraf <span class="math inline">\(1-\alpha\)</span>) av</p>
<p><span class="math display">\[\bar y \pm t_{(1-\alpha/2,n-1)} \frac{s}{\sqrt n}\]</span></p>
<p>Kvantilen från t-fördelningen kan hämtas från en tabell (samma som det kritiska värdet i testet) eller genom R. Antalet frihetsgrader ges av antalet observationer minus ett. I det här fallet ges delarna av</p>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb119-1" tabindex="-1"></a><span class="fu">mean</span>(dat<span class="sc">$</span>y)</span>
<span id="cb119-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb119-2" tabindex="-1"></a><span class="fu">sd</span>(dat<span class="sc">$</span>y)</span>
<span id="cb119-3"><a href="ett-stickprov-av-normalfördelad-data.html#cb119-3" tabindex="-1"></a><span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="dv">7</span>)</span></code></pre></div>
<p>och konfidensintervallet ges alltså av</p>
<p><span class="math display">\[52 \pm 2.365 \cdot 4.680 / \sqrt 8\]</span></p>
<p>Funktionen <code>t.test()</code> ger automatiskt ett konfidensintervall, direkt under utfallet av testet. Notera att konfidensintervallet inte beror på nollhypotesen. Konfidensintervall kan beräknas med skilda konfidensnivåer, oftast 95 procent, vilket sätts med argumentet <code>conf.level</code>.</p>
<div class="exercise">
<p><span id="exr:unlabeled-div-47" class="exercise"><strong>Uppgift 3.5  (Konfidensnivå) </strong></span>Gör lämplig ändring i koden nedan för att beräkna ett 99-procentigt konfidensintervall, istället för ett 95-procentigt.</p>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb120-1" tabindex="-1"></a><span class="fu">t.test</span>(dat<span class="sc">$</span>y, <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  dat$y
## t = 31.425, df = 7, p-value = 8.538e-09
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  48.08713 55.91287
## sample estimates:
## mean of x 
##        52</code></pre>
<p>Är ett 99-procentigt konfidensintervall bredare eller smalare än ett 95-procentigt?</p>
</div>
</div>
<div id="normalfördelad-data" class="section level2 hasAnchor" number="3.4">
<h2><span class="header-section-number">3.4</span> Normalfördelad data<a href="#normalf%C3%B6rdelad-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Eftersom t-testet bygger på att data är normalfördelad är det förstås bra att kunna undersöka om det antagandet stämmer. Ett sätt är att göra ett histogram över datan - om den underliggande variabeln är normalfördelad bör stickprovet ge den typiska klockformen. Det här kräver dock ganska mycket data. Ta ett histogram för havredatan som exempel</p>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb122-1" tabindex="-1"></a><span class="fu">ggplot</span>(dat, <span class="fu">aes</span>(y)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">5</span>)</span></code></pre></div>
<p>Låt oss titta på histogram över genererad normalfördelad data.</p>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb123-1" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb123-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb123-2" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">rnorm</span>(n)), <span class="at">bins =</span> <span class="dv">30</span>)</span></code></pre></div>
<div class="exercise">
<p><span id="exr:unlabeled-div-48" class="exercise"><strong>Uppgift 3.6  (Histogram för normalfördelning) </strong></span>Testa koden ovan för lite olika värden på <code>n</code>. Det kan vara nyttigt att sätta antalet staplar <code>bins</code> för att få ett bättre histogram. Hur stort måste <code>n</code> vara för att ge en karaktäristisk klockform för histogrammet?</p>
</div>
<p>Ett annat vanligt alternativ för att grafisk undersöka om data följer en ungefärlig normalfördelning är en QQ-graf (<em>QQ-plot</em>). En qq-graf är ett spridningsdiagram med teoretiska kvantiler på en axel och datans kvantiler på den andra axeln. Om data perfekt följer en normalfördelning kommer grafen visa en rak diagonal linje. En QQ-graf kan tas fram med <code>qqnorm()</code> eller <code>geom_qq()</code> i en ggplot. En diagonal linje för jämförelse kan läggas till med <code>geom_qq_line()</code>.</p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb124-1" tabindex="-1"></a><span class="fu">ggplot</span>(dat, <span class="fu">aes</span>(<span class="at">sample =</span> y)) <span class="sc">+</span> <span class="fu">geom_qq</span>() <span class="sc">+</span> <span class="fu">geom_qq_line</span>()</span></code></pre></div>
<p>Punkterna ligger nära linjen. Vi kan återigen demonstrera med lite genererad data.</p>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb125-1" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">100</span></span>
<span id="cb125-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb125-2" tabindex="-1"></a>dat_norm <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">y =</span> <span class="fu">rnorm</span>(n))</span>
<span id="cb125-3"><a href="ett-stickprov-av-normalfördelad-data.html#cb125-3" tabindex="-1"></a><span class="fu">ggplot</span>(dat_norm, <span class="fu">aes</span>(<span class="at">sample =</span> y)) <span class="sc">+</span> <span class="fu">geom_qq</span>() <span class="sc">+</span> <span class="fu">geom_qq_line</span>()</span></code></pre></div>
<div class="exercise">
<p><span id="exr:unlabeled-div-49" class="exercise"><strong>Uppgift 3.7  (Histogram för normalfördelning) </strong></span>Funktionen <code>runif()</code> ger slumpmässiga värden mellan 0 och 1. Testa att ändra i kodstycket ovan så att slumptal genereras med <code>runif()</code> istället för <code>rnorm()</code>. Hur påverkar det QQ-grafen?</p>
</div>
</div>
<div id="centrala-gränsvärdesatsen" class="section level2 hasAnchor" number="3.5">
<h2><span class="header-section-number">3.5</span> Centrala gränsvärdesatsen<a href="#centrala-gr%C3%A4nsv%C3%A4rdesatsen" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Även om data inte är normalfördelad kan t-testet vara ett lämpligt val av test. Detta beror på <em>centrala gränsvärdesatsen</em>, som säger att summor (och därmed även medelvärden) av lika slumpvariabler går mot en normalfördelning där antalet observationer ökar. Den tidigare uppgiften gav att <code>runif()</code> inte ger normalfördelad data. Vad händer om vi tar medelvärdet av flera observationer från <code>runif()</code>? Följande kod beräknar tiotusen medelvärden av två observationer.</p>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb126-1" tabindex="-1"></a>antal <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb126-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb126-2" tabindex="-1"></a></span>
<span id="cb126-3"><a href="ett-stickprov-av-normalfördelad-data.html#cb126-3" tabindex="-1"></a>dat_sim_unif <span class="ot">&lt;-</span> <span class="fu">expand_grid</span>(<span class="at">Observation =</span> <span class="dv">1</span><span class="sc">:</span>antal, </span>
<span id="cb126-4"><a href="ett-stickprov-av-normalfördelad-data.html#cb126-4" tabindex="-1"></a>                            <span class="at">Upprepning =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10000</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb126-5"><a href="ett-stickprov-av-normalfördelad-data.html#cb126-5" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">y =</span> <span class="fu">runif</span>(<span class="fu">n</span>())) <span class="sc">%&gt;%</span> </span>
<span id="cb126-6"><a href="ett-stickprov-av-normalfördelad-data.html#cb126-6" tabindex="-1"></a>  <span class="fu">group_by</span>(Upprepning) <span class="sc">%&gt;%</span> </span>
<span id="cb126-7"><a href="ett-stickprov-av-normalfördelad-data.html#cb126-7" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">y =</span> <span class="fu">mean</span>(y))</span>
<span id="cb126-8"><a href="ett-stickprov-av-normalfördelad-data.html#cb126-8" tabindex="-1"></a></span>
<span id="cb126-9"><a href="ett-stickprov-av-normalfördelad-data.html#cb126-9" tabindex="-1"></a><span class="fu">ggplot</span>(dat_sim_unif, <span class="fu">aes</span>(y)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">50</span>)</span></code></pre></div>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb127-1" tabindex="-1"></a><span class="fu">ggplot</span>(dat_sim_unif, <span class="fu">aes</span>(<span class="at">sample =</span> y)) <span class="sc">+</span> </span>
<span id="cb127-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb127-2" tabindex="-1"></a>  <span class="fu">geom_qq</span>() <span class="sc">+</span> <span class="fu">geom_qq_line</span>()</span></code></pre></div>
<p>Fördelningen för summan är inte likformig, men inte heller särskilt normalfördelad. Vad händer om vi ökar antal termer i summan?</p>
<div class="exercise">
<p><span id="exr:unlabeled-div-50" class="exercise"><strong>Uppgift 3.8  (Antalet observationer för normalfördelning) </strong></span>Vad måste ändras i koden ovan för beräkna medelvärdet av tio observationer? Följer de medelvärdena en ungefärlig normalfördelning? Vad är det lägsta antalet observationer som ger ungefärligen normalfördelade medelvärden?</p>
</div>
<p>Det kan också finnas situationer där någon matematisk transformation kan göra icke-normal data till normalfördelad data. Vanliga transformationer är att ta en kvadratrot eller att <em>logaritmera</em> datan. Som exempel kan vi återvända till gapminder-datan vi använde i en tidigare datorövning. Paketet <code>patchwork</code> kan användas för att placera flera grafer bredvid varandra. Den exakta koden är mindre viktig här.</p>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb128-1" tabindex="-1"></a><span class="fu">library</span>(gapminder)</span>
<span id="cb128-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb128-2" tabindex="-1"></a>gapminder_2007 <span class="ot">&lt;-</span> gapminder <span class="sc">%&gt;%</span> <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">2007</span>)</span>
<span id="cb128-3"><a href="ett-stickprov-av-normalfördelad-data.html#cb128-3" tabindex="-1"></a></span>
<span id="cb128-4"><a href="ett-stickprov-av-normalfördelad-data.html#cb128-4" tabindex="-1"></a>g1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(gapminder_2007, <span class="fu">aes</span>(pop)) <span class="sc">+</span> </span>
<span id="cb128-5"><a href="ett-stickprov-av-normalfördelad-data.html#cb128-5" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">30</span>)</span>
<span id="cb128-6"><a href="ett-stickprov-av-normalfördelad-data.html#cb128-6" tabindex="-1"></a>g2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(gapminder_2007, <span class="fu">aes</span>(<span class="at">sample =</span> pop)) <span class="sc">+</span> </span>
<span id="cb128-7"><a href="ett-stickprov-av-normalfördelad-data.html#cb128-7" tabindex="-1"></a>  <span class="fu">geom_qq</span>() <span class="sc">+</span> </span>
<span id="cb128-8"><a href="ett-stickprov-av-normalfördelad-data.html#cb128-8" tabindex="-1"></a>  <span class="fu">geom_qq_line</span>()</span>
<span id="cb128-9"><a href="ett-stickprov-av-normalfördelad-data.html#cb128-9" tabindex="-1"></a>g3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(gapminder_2007, <span class="fu">aes</span>(<span class="fu">sqrt</span>(pop))) <span class="sc">+</span> </span>
<span id="cb128-10"><a href="ett-stickprov-av-normalfördelad-data.html#cb128-10" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">30</span>)</span>
<span id="cb128-11"><a href="ett-stickprov-av-normalfördelad-data.html#cb128-11" tabindex="-1"></a>g4 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(gapminder_2007, <span class="fu">aes</span>(<span class="at">sample =</span> <span class="fu">sqrt</span>(pop))) <span class="sc">+</span> </span>
<span id="cb128-12"><a href="ett-stickprov-av-normalfördelad-data.html#cb128-12" tabindex="-1"></a>  <span class="fu">geom_qq</span>() <span class="sc">+</span> </span>
<span id="cb128-13"><a href="ett-stickprov-av-normalfördelad-data.html#cb128-13" tabindex="-1"></a>  <span class="fu">geom_qq_line</span>()</span>
<span id="cb128-14"><a href="ett-stickprov-av-normalfördelad-data.html#cb128-14" tabindex="-1"></a>g5 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(gapminder_2007, <span class="fu">aes</span>(<span class="fu">log10</span>(pop))) <span class="sc">+</span> </span>
<span id="cb128-15"><a href="ett-stickprov-av-normalfördelad-data.html#cb128-15" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">30</span>)</span>
<span id="cb128-16"><a href="ett-stickprov-av-normalfördelad-data.html#cb128-16" tabindex="-1"></a>g6 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(gapminder_2007, <span class="fu">aes</span>(<span class="at">sample =</span> <span class="fu">log10</span>(pop))) <span class="sc">+</span> </span>
<span id="cb128-17"><a href="ett-stickprov-av-normalfördelad-data.html#cb128-17" tabindex="-1"></a>  <span class="fu">geom_qq</span>() <span class="sc">+</span> </span>
<span id="cb128-18"><a href="ett-stickprov-av-normalfördelad-data.html#cb128-18" tabindex="-1"></a>  <span class="fu">geom_qq_line</span>()</span>
<span id="cb128-19"><a href="ett-stickprov-av-normalfördelad-data.html#cb128-19" tabindex="-1"></a></span>
<span id="cb128-20"><a href="ett-stickprov-av-normalfördelad-data.html#cb128-20" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb128-21"><a href="ett-stickprov-av-normalfördelad-data.html#cb128-21" tabindex="-1"></a>g1 <span class="sc">+</span> g3 <span class="sc">+</span> g5 <span class="sc">+</span> g2 <span class="sc">+</span> g4 <span class="sc">+</span> g6</span></code></pre></div>
<p>I grafen har vi den ursprungliga variabeln (befolkning per land 2007), den kvadratrot-transformerade variabeln (<code>sqrt()</code>) och den log-transformerade variabeln (<code>log10()</code>). De två första fallen påverkas kraftigt av extremvärden och är klart icke-normala medan den log-transformerade variabeln ger en ungefärlig normalkurva och följer diagonalen väl i QQ-grafen.</p>
</div>
<div id="ai-uppgift-iii" class="section level2 hasAnchor" number="3.6">
<h2><span class="header-section-number">3.6</span> AI-uppgift III<a href="ett-stickprov-av-normalfördelad-data.html#ai-uppgift-iii" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Det finns många studier som pekar på att p-värdet är svårtolkat. Det är särskilt vanligt att p-värdet tolkas som sannolikheten att nollhypotesen är sann. Den korrekta tolkningen är dock snarare tvärtom: p-värdet är sannolikheten för datautfallet givet att nollhypotesen är sann.</p>
<div class="exercise">
<p><span id="exr:unlabeled-div-51" class="exercise"><strong>Uppgift 3.9  (Tolkning av p-värdet) </strong></span>Be en AI-chatbot besvara en t-test-fråga t.ex. från en tidigare tenta eller uppgiften i början av den här övningen. Fråga särskilt om tolkningen av p-värdet och om det finns några vanliga feltolkningar.</p>
</div>
</div>
<div id="bonus.-simuleringar-för-t-test" class="section level2 hasAnchor" number="3.7">
<h2><span class="header-section-number">3.7</span> Bonus. Simuleringar för t-test<a href="#bonus.-simuleringar-f%C3%B6r-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Följande kod simulerar ett dataset om tio observationer från en normalfördelning med medelvärde 7 och standardavvikelse 5, beräknar ett hypotestest med nollhypotesen att populationsmedelvärdet är 7, och beräknar ett konfidensintervall.</p>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb129-1" tabindex="-1"></a>dat_sim <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">y =</span> <span class="fu">rnorm</span>(<span class="dv">10</span>, <span class="at">mean =</span> <span class="dv">7</span>, <span class="at">sd =</span> <span class="dv">5</span>))</span>
<span id="cb129-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb129-2" tabindex="-1"></a><span class="fu">t.test</span>(dat_sim<span class="sc">$</span>y, <span class="at">mu =</span> <span class="dv">7</span>)</span></code></pre></div>
<div class="exercise">
<p><span id="exr:unlabeled-div-52" class="exercise"><strong>Uppgift 3.10  (Upprepad simulering) </strong></span>Kör de två raderna i stycket ovan ett tiotal gånger. Du bör se att man ibland förkastar nollhypotesen trots att den ska stämma. Kan du få en känsla för hur stor andel av gångerna man felaktigt förkastar?</p>
</div>
<p>Låt oss upprepa simuleringen tusen gånger. Ett sätt är att upprepa ett steg flera gånger är genom en for-loop.</p>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb130-1" tabindex="-1"></a>dat_sim <span class="ot">&lt;-</span> <span class="fu">data.frame</span>()</span>
<span id="cb130-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb130-2" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span>){</span>
<span id="cb130-3"><a href="ett-stickprov-av-normalfördelad-data.html#cb130-3" tabindex="-1"></a>  new_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">y =</span> <span class="fu">rnorm</span>(<span class="dv">10</span>, <span class="at">mean =</span> <span class="dv">7</span>, <span class="at">sd =</span> <span class="dv">5</span>))</span>
<span id="cb130-4"><a href="ett-stickprov-av-normalfördelad-data.html#cb130-4" tabindex="-1"></a>  test <span class="ot">&lt;-</span> <span class="fu">t.test</span>(new_data<span class="sc">$</span>y, <span class="at">mu =</span> <span class="dv">7</span>)</span>
<span id="cb130-5"><a href="ett-stickprov-av-normalfördelad-data.html#cb130-5" tabindex="-1"></a>  new_results <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">t_value =</span> test<span class="sc">$</span>statistic, </span>
<span id="cb130-6"><a href="ett-stickprov-av-normalfördelad-data.html#cb130-6" tabindex="-1"></a>                            <span class="at">p_value =</span> test<span class="sc">$</span>p.value,</span>
<span id="cb130-7"><a href="ett-stickprov-av-normalfördelad-data.html#cb130-7" tabindex="-1"></a>                            <span class="at">ci_lower =</span> test<span class="sc">$</span>conf.int[<span class="dv">1</span>], </span>
<span id="cb130-8"><a href="ett-stickprov-av-normalfördelad-data.html#cb130-8" tabindex="-1"></a>                            <span class="at">ci_upper =</span> test<span class="sc">$</span>conf.int[<span class="dv">2</span>])</span>
<span id="cb130-9"><a href="ett-stickprov-av-normalfördelad-data.html#cb130-9" tabindex="-1"></a>  dat_sim <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(dat_sim, new_results)</span>
<span id="cb130-10"><a href="ett-stickprov-av-normalfördelad-data.html#cb130-10" tabindex="-1"></a>}</span></code></pre></div>
<p>Enligt statistisk teori ska t-värdet följa en t-fördelning med nio frihetsgrader. Vi kan undersöka det genom ett histogram.</p>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb131-1" tabindex="-1"></a><span class="fu">ggplot</span>(dat_sim) <span class="sc">+</span></span>
<span id="cb131-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb131-2" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(t_value, <span class="at">y =</span> <span class="fu">after_stat</span>(density)), </span>
<span id="cb131-3"><a href="ett-stickprov-av-normalfördelad-data.html#cb131-3" tabindex="-1"></a>                 <span class="at">bins =</span> <span class="dv">50</span>, </span>
<span id="cb131-4"><a href="ett-stickprov-av-normalfördelad-data.html#cb131-4" tabindex="-1"></a>                 <span class="at">fill =</span> <span class="st">&quot;white&quot;</span>, <span class="at">color =</span> <span class="st">&quot;black&quot;</span>) <span class="sc">+</span></span>
<span id="cb131-5"><a href="ett-stickprov-av-normalfördelad-data.html#cb131-5" tabindex="-1"></a>  <span class="fu">geom_function</span>(<span class="at">fun =</span> dt, <span class="at">args =</span> <span class="fu">list</span>(<span class="at">df =</span> <span class="dv">9</span>))</span></code></pre></div>
<p>Den teoretiska t-fördelning passar histogrammet nästan perfekt.</p>
<p>Vidare ska p-värdet vara under fem procent fem procent av gångerna.</p>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb132-1" tabindex="-1"></a><span class="fu">mean</span>(dat_sim<span class="sc">$</span>p_value <span class="sc">&lt;</span> <span class="fl">0.05</span>)</span></code></pre></div>
<p>Även det stämmer någorlunda väl. Det här innebär alltså att om man har en signifikansnivå på fem procent kommer man förkasta nollhypotesen fem procent av gångerna även om nollhypotesen stämmer. Det kallas ett <em>falskt positivt</em> utfall.</p>
<div class="exercise">
<p><span id="exr:unlabeled-div-53" class="exercise"><strong>Uppgift 3.11  (Signifikant skillnad) </strong></span>Stycket nedan simulerar data när populationsmedelvärdet är 9 och t-test har nollhypotesen att populationsmedelvärdet är 7. Här vill vi alltså förkasta nollhypotesen.</p>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb133-1" tabindex="-1"></a>dat_sim <span class="ot">&lt;-</span> <span class="fu">data.frame</span>()</span>
<span id="cb133-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb133-2" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span>){</span>
<span id="cb133-3"><a href="ett-stickprov-av-normalfördelad-data.html#cb133-3" tabindex="-1"></a>  new_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">y =</span> <span class="fu">rnorm</span>(<span class="dv">10</span>, <span class="at">mean =</span> <span class="dv">9</span>, <span class="at">sd =</span> <span class="dv">5</span>))</span>
<span id="cb133-4"><a href="ett-stickprov-av-normalfördelad-data.html#cb133-4" tabindex="-1"></a>  test <span class="ot">&lt;-</span> <span class="fu">t.test</span>(new_data<span class="sc">$</span>y, <span class="at">mu =</span> <span class="dv">7</span>)</span>
<span id="cb133-5"><a href="ett-stickprov-av-normalfördelad-data.html#cb133-5" tabindex="-1"></a>  new_results <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">t_value =</span> test<span class="sc">$</span>statistic, </span>
<span id="cb133-6"><a href="ett-stickprov-av-normalfördelad-data.html#cb133-6" tabindex="-1"></a>                            <span class="at">p_value =</span> test<span class="sc">$</span>p.value,</span>
<span id="cb133-7"><a href="ett-stickprov-av-normalfördelad-data.html#cb133-7" tabindex="-1"></a>                            <span class="at">ci_lower =</span> test<span class="sc">$</span>conf.int[<span class="dv">1</span>], </span>
<span id="cb133-8"><a href="ett-stickprov-av-normalfördelad-data.html#cb133-8" tabindex="-1"></a>                            <span class="at">ci_upper =</span> test<span class="sc">$</span>conf.int[<span class="dv">2</span>])</span>
<span id="cb133-9"><a href="ett-stickprov-av-normalfördelad-data.html#cb133-9" tabindex="-1"></a>  dat_sim <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(dat_sim, new_results)</span>
<span id="cb133-10"><a href="ett-stickprov-av-normalfördelad-data.html#cb133-10" tabindex="-1"></a>}</span></code></pre></div>
<p>Använd kod från den första simuleringen för att undersöka hur väl histogrammet stämmer med den teoretiska fördelningen och för att se hur stor andel av gångerna man förkastar nollhypotesen på signifikansnivån 5 procent.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-54" class="exercise"><strong>Uppgift 3.12  (Konfidensintervallets bredd) </strong></span>Ett konfidensintervall blir smalare och smalare ju större stickprovet är. Koden nedan ger medelvärdet för stickprovsbredden i simulerad data med standardavvikelsen 1.</p>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb134-1" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb134-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb134-2" tabindex="-1"></a></span>
<span id="cb134-3"><a href="ett-stickprov-av-normalfördelad-data.html#cb134-3" tabindex="-1"></a>dat_sim <span class="ot">&lt;-</span> <span class="fu">data.frame</span>()</span>
<span id="cb134-4"><a href="ett-stickprov-av-normalfördelad-data.html#cb134-4" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span>){</span>
<span id="cb134-5"><a href="ett-stickprov-av-normalfördelad-data.html#cb134-5" tabindex="-1"></a>  new_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">y =</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>))</span>
<span id="cb134-6"><a href="ett-stickprov-av-normalfördelad-data.html#cb134-6" tabindex="-1"></a>  test <span class="ot">&lt;-</span> <span class="fu">t.test</span>(new_data<span class="sc">$</span>y, <span class="at">mu =</span> <span class="dv">7</span>)</span>
<span id="cb134-7"><a href="ett-stickprov-av-normalfördelad-data.html#cb134-7" tabindex="-1"></a>  new_results <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">t_value =</span> test<span class="sc">$</span>statistic, </span>
<span id="cb134-8"><a href="ett-stickprov-av-normalfördelad-data.html#cb134-8" tabindex="-1"></a>                            <span class="at">p_value =</span> test<span class="sc">$</span>p.value,</span>
<span id="cb134-9"><a href="ett-stickprov-av-normalfördelad-data.html#cb134-9" tabindex="-1"></a>                            <span class="at">ci_lower =</span> test<span class="sc">$</span>conf.int[<span class="dv">1</span>], </span>
<span id="cb134-10"><a href="ett-stickprov-av-normalfördelad-data.html#cb134-10" tabindex="-1"></a>                            <span class="at">ci_upper =</span> test<span class="sc">$</span>conf.int[<span class="dv">2</span>])</span>
<span id="cb134-11"><a href="ett-stickprov-av-normalfördelad-data.html#cb134-11" tabindex="-1"></a>  dat_sim <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(dat_sim, new_results)</span>
<span id="cb134-12"><a href="ett-stickprov-av-normalfördelad-data.html#cb134-12" tabindex="-1"></a>}</span>
<span id="cb134-13"><a href="ett-stickprov-av-normalfördelad-data.html#cb134-13" tabindex="-1"></a></span>
<span id="cb134-14"><a href="ett-stickprov-av-normalfördelad-data.html#cb134-14" tabindex="-1"></a><span class="fu">mean</span>(dat_sim<span class="sc">$</span>ci_upper <span class="sc">-</span> dat_sim<span class="sc">$</span>ci_lower)</span></code></pre></div>
<p>Ungefär hur många observationer behövs för att konfidensintervallets bredd ska bli under 1, under 0.9, under 0.8, och så vidare ned till 0.1?</p>
</div>
</div>
<div id="ett-stickprov-av-icke-normalfördelad-data" class="section level2 hasAnchor" number="3.8">
<h2><span class="header-section-number">3.8</span> Ett stickprov av icke-normalfördelad data<a href="#ett-stickprov-av-icke-normalf%C3%B6rdelad-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Datorövning 4 handlar om hypotestest och konfidensintervall för ett stickprov av icke-normalfördelad data. Efter övningen ska vi kunna</p>
<ul>
<li><p>genomföra och tolka ett z-test för proportioner,</p></li>
<li><p>genomföra och tolka ett chi-två-test för nominal data</p></li>
<li><p>beräkna och tolka ett konfidensintervall för proportioner.</p></li>
</ul>
<p>Om det finns tid för en bonussektion kommer vi också titta på interaktiva kartor med <code>leaflet</code>.</p>
</div>
<div id="repetition-av-datorövning-3" class="section level2 hasAnchor" number="3.9">
<h2><span class="header-section-number">3.9</span> Repetition av datorövning 3<a href="#repetition-av-dator%C3%B6vning-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>När man startar en ny R-session bör man ladda de paket man vet kommer behövas med <code>library()</code>. Om paket inte finns installerade måste man först köra <code>install.packages()</code>.</p>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb135-1" tabindex="-1"></a><span class="co"># install.packages(&quot;tidyverse&quot;)</span></span>
<span id="cb135-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb135-2" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
<p>I datorövning 3 tittade vi på analys av ett stickprov av normalfördelad data. Det underliggande upplägget är att vi vill säga något om en population genom att titta på ett stickprov. Ett <em>t-test</em> kan användas för att testa en given <em>nollhypotes</em>. Ett konfidensintervall ringar in populationens medelvärde med en viss konfidensgrad - oftast 95 procent. Ett normalfördelningsantagande kan undersökas med histogram eller QQ-grafer.</p>
<p>Ta som exempel följande data på jord-pH och låt oss anta att det är relevant att testa om populationens medelvärde är 7.</p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb136-1" tabindex="-1"></a>dat_pH <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">pH =</span> <span class="fu">c</span>(<span class="fl">6.3</span>, <span class="fl">6.55</span>, <span class="fl">6.75</span>, <span class="fl">6.4</span>, </span>
<span id="cb136-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb136-2" tabindex="-1"></a>                            <span class="fl">7.25</span>, <span class="fl">6.65</span>, <span class="fl">6.8</span>, <span class="fl">7.3</span>, <span class="fl">7.15</span>, <span class="fl">6.7</span>))</span>
<span id="cb136-3"><a href="ett-stickprov-av-normalfördelad-data.html#cb136-3" tabindex="-1"></a></span>
<span id="cb136-4"><a href="ett-stickprov-av-normalfördelad-data.html#cb136-4" tabindex="-1"></a><span class="fu">ggplot</span>(dat_pH, <span class="fu">aes</span>(pH, <span class="dv">0</span>)) <span class="sc">+</span></span>
<span id="cb136-5"><a href="ett-stickprov-av-normalfördelad-data.html#cb136-5" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb136-6"><a href="ett-stickprov-av-normalfördelad-data.html#cb136-6" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">7</span>, <span class="at">size =</span> <span class="dv">5</span>, </span>
<span id="cb136-7"><a href="ett-stickprov-av-normalfördelad-data.html#cb136-7" tabindex="-1"></a>             <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb136-8"><a href="ett-stickprov-av-normalfördelad-data.html#cb136-8" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.y =</span> <span class="fu">element_blank</span>(), </span>
<span id="cb136-9"><a href="ett-stickprov-av-normalfördelad-data.html#cb136-9" tabindex="-1"></a>        <span class="at">axis.title.y =</span> <span class="fu">element_blank</span>(), </span>
<span id="cb136-10"><a href="ett-stickprov-av-normalfördelad-data.html#cb136-10" tabindex="-1"></a>        <span class="at">axis.ticks =</span> <span class="fu">element_blank</span>())</span></code></pre></div>
<p>Hypoteser ges av</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu\)</span> lika med 7</li>
<li><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\mu\)</span> ej lika med 7</li>
</ul>
<p>Testet kan genomföras med funktionen <code>t.test()</code>.</p>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb137-1" tabindex="-1"></a><span class="fu">t.test</span>(dat_pH<span class="sc">$</span>pH, <span class="at">mu =</span> <span class="dv">7</span>)</span></code></pre></div>
<p>Ett p-värde över 0.05 ger att vi inte förkastar nollhypotesen - den observerade skillnaden mot 7 är inte statistiskt signifikant. Konfidensintervallet ger att populationens medelvärde ligger mellan 6.54 och 7.03 med 95 procents konfidens.</p>
<p>En QQ-graf kan visa om det finns några avvikelser från normalantagandet. Med små datamängder är det oftast svårt att se några tydliga tecken på icke-normalitet.</p>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb138-1" tabindex="-1"></a><span class="fu">ggplot</span>(dat_pH, <span class="fu">aes</span>(<span class="at">sample =</span> pH)) <span class="sc">+</span></span>
<span id="cb138-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb138-2" tabindex="-1"></a>  <span class="fu">geom_qq</span>() <span class="sc">+</span></span>
<span id="cb138-3"><a href="ett-stickprov-av-normalfördelad-data.html#cb138-3" tabindex="-1"></a>  <span class="fu">geom_qq_line</span>()</span></code></pre></div>
</div>
<div id="proportioner-från-binär-data" class="section level2 hasAnchor" number="3.10">
<h2><span class="header-section-number">3.10</span> Proportioner från binär data<a href="#proportioner-fr%C3%A5n-bin%C3%A4r-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Binär data är data där en observation har ett av två utfall, vilka kan kodas som noll och ett. Man talar ibland om utfallet ett som ett <em>positivt</em> utfall. Binär data kan sammanfattas med en proportion - antalet positiva utfall delat på det totala antalet upprepningar. En proportion kan testas med ett z-test för proportioner (eller <em>relativ frekvens</em>). Testet följer stegen för hypotestest (Hypoteser - Testvärde - Testfördelning - P-värde (eller jämförelse med kritiskt värde) - Slutsats).</p>
<p>Låt oss importera lite exempeldata och beräkna ett exempel. Följande rad importerar matchresultat i fotbollsallsvenskan för damer 2000-2020.</p>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb139-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb139-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb139-2" tabindex="-1"></a>dat_alls <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;https://raw.githubusercontent.com/adamflr/ST0060/main/Data/Allsvenskan%2C%20damer%2C%202000-2020.csv&quot;</span>)</span>
<span id="cb139-3"><a href="ett-stickprov-av-normalfördelad-data.html#cb139-3" tabindex="-1"></a></span>
<span id="cb139-4"><a href="ett-stickprov-av-normalfördelad-data.html#cb139-4" tabindex="-1"></a><span class="fu">ggplot</span>(dat_alls, <span class="fu">aes</span>(hemmamal, bortamal)) <span class="sc">+</span></span>
<span id="cb139-5"><a href="ett-stickprov-av-normalfördelad-data.html#cb139-5" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">size =</span> <span class="fl">0.1</span>)</span></code></pre></div>
<div class="exercise">
<p><span id="exr:unlabeled-div-55" class="exercise"><strong>Uppgift 3.13  (En interaktiv målgraf) </strong></span>Kör stycket nedan för en interaktiv målgraf. Vilken match gav det högsta antalet gjorda bortamål?</p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb140-1" tabindex="-1"></a><span class="co"># install.packages(&quot;plotly&quot;)</span></span>
<span id="cb140-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb140-2" tabindex="-1"></a><span class="fu">library</span>(plotly)</span>
<span id="cb140-3"><a href="ett-stickprov-av-normalfördelad-data.html#cb140-3" tabindex="-1"></a>g <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(dat_alls, <span class="fu">aes</span>(hemmamal, bortamal, </span>
<span id="cb140-4"><a href="ett-stickprov-av-normalfördelad-data.html#cb140-4" tabindex="-1"></a>                      <span class="at">text =</span> <span class="fu">paste</span>(sasong, hemma, <span class="st">&quot;-&quot;</span>, borta))) <span class="sc">+</span></span>
<span id="cb140-5"><a href="ett-stickprov-av-normalfördelad-data.html#cb140-5" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">size =</span> <span class="fl">0.1</span>)</span>
<span id="cb140-6"><a href="ett-stickprov-av-normalfördelad-data.html#cb140-6" tabindex="-1"></a></span>
<span id="cb140-7"><a href="ett-stickprov-av-normalfördelad-data.html#cb140-7" tabindex="-1"></a><span class="fu">ggplotly</span>(g)</span></code></pre></div>
</div>
<p>Gammal bollkunskap säger att var tredje match är en bortavinst. Vi kan testa det med ett z-test för proportioner. För att ta fram antalet bortasegrar och totalt antal matcher använder vi <code>count()</code> på kolumnen <code>resultat</code>. Man kan också använda funktionen <code>table()</code> för ett liknande resultat.</p>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb141-1" tabindex="-1"></a>dat_alls <span class="sc">%&gt;%</span> <span class="fu">count</span>(resultat)</span>
<span id="cb141-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb141-2" tabindex="-1"></a><span class="fu">table</span>(dat_alls<span class="sc">$</span>resultat)</span></code></pre></div>
<p>Datan har 947 bortasegrar av totalt 947 + 1803 matcher. Vår skattade proportion <code>p</code> och totala antal <code>n</code> är alltså</p>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb142-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb142-1" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">947</span> <span class="sc">+</span> <span class="dv">1803</span></span>
<span id="cb142-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb142-2" tabindex="-1"></a>p_est <span class="ot">&lt;-</span> <span class="dv">947</span> <span class="sc">/</span> n</span>
<span id="cb142-3"><a href="ett-stickprov-av-normalfördelad-data.html#cb142-3" tabindex="-1"></a></span>
<span id="cb142-4"><a href="ett-stickprov-av-normalfördelad-data.html#cb142-4" tabindex="-1"></a>p_est</span>
<span id="cb142-5"><a href="ett-stickprov-av-normalfördelad-data.html#cb142-5" tabindex="-1"></a>n</span></code></pre></div>
<p>För att genomföra ett z-test sätter vi upp hypoteser om proportionen bortasegrar.</p>
<ul>
<li>Nollhypotes <span class="math inline">\(H_0\)</span>: p lika med 0.33</li>
<li>Alternativhypotes <span class="math inline">\(H_1\)</span>: p ej lika med 0.33</li>
</ul>
<p>Ett test kan köras i R med <code>prop.test()</code>.</p>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb143-1" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="at">x =</span> <span class="dv">947</span>, <span class="at">n =</span> <span class="dv">2750</span>, <span class="at">p =</span> <span class="fl">0.33</span>, <span class="at">correct =</span> F)</span></code></pre></div>
<pre><code>## 
##  1-sample proportions test without continuity correction
## 
## data:  947 out of 2750, null probability 0.33
## X-squared = 2.5661, df = 1, p-value = 0.1092
## alternative hypothesis: true p is not equal to 0.33
## 95 percent confidence interval:
##  0.3268327 0.3623288
## sample estimates:
##         p 
## 0.3443636</code></pre>
<p>P-värdet ställs mot en förbestämd signifikansnivå (vanligen 5 procent). I det här fallet leder det höga p-värdet till att nollhypotesen accepteras.</p>
<p>Om vi tar en närmre titt på testets steg börjar vi med att beräkna ett testvärde.</p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb145-1" tabindex="-1"></a>p0 <span class="ot">&lt;-</span> <span class="fl">0.33</span></span>
<span id="cb145-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb145-2" tabindex="-1"></a>z_value <span class="ot">&lt;-</span> (p_est <span class="sc">-</span> p0) <span class="sc">/</span> <span class="fu">sqrt</span>(p0 <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p0) <span class="sc">/</span> n)</span>
<span id="cb145-3"><a href="ett-stickprov-av-normalfördelad-data.html#cb145-3" tabindex="-1"></a>z_value</span></code></pre></div>
<pre><code>## [1] 1.601904</code></pre>
<p>Därefter kan p-värdet räknas ut som arean under en standardiserad normalfördelning bortom z-värdet. Eftersom vi har en tvåsidig mothypotes adderas de två svansarna.</p>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb147-1" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb147-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb147-2" tabindex="-1"></a>  <span class="fu">geom_function</span>(<span class="at">fun =</span> dnorm) <span class="sc">+</span></span>
<span id="cb147-3"><a href="ett-stickprov-av-normalfördelad-data.html#cb147-3" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">c</span>(<span class="sc">-</span>z_value, z_value)) <span class="sc">+</span></span>
<span id="cb147-4"><a href="ett-stickprov-av-normalfördelad-data.html#cb147-4" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="sc">-</span><span class="dv">3</span>,<span class="dv">3</span>)</span></code></pre></div>
<p>Areans yta kan tas fram med normalfördelningens fördelningsfunktion <code>pnorm()</code>.</p>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb148-1" tabindex="-1"></a><span class="dv">2</span> <span class="sc">*</span> <span class="fu">pnorm</span>(<span class="sc">-</span>z_value)</span></code></pre></div>
<pre><code>## [1] 0.1091769</code></pre>
<p>Testets p-värde är ungefär 11 procent. Vår observation är alltså inte ett orimligt utfall om den faktiska sannolikheten för bortaseger är 0.33 och vi kan inte förkasta nollhypotesen på femprocentsnivån.</p>
<p>Om man löste uppgiften för hand skulle man istället för att beräkna p-värdet jämföra z-värdet med ett kritisk värde ur en tabell. Det kritiska värdet för femprocentig signifikans är 1.96. Vi kan också ta fram det genom <code>qnorm(0.975)</code>.</p>
<p>Vi kan jämföra den beräkning med den direkta R-funktionen.</p>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb150-1" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="at">x =</span> <span class="dv">947</span>, <span class="at">n =</span> <span class="dv">2750</span>, <span class="at">p =</span> <span class="fl">0.33</span>, <span class="at">correct =</span> F)</span></code></pre></div>
<p>Den stegvisa beräkningen gav samma utfall som funktionen (<code>p-value = 0.1092</code>). Funktionen ger inte z-värdet utan ett chi-två-värde (2.5661). Här är det värdet lika med z-värdet i kvadrat.</p>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb151-1" tabindex="-1"></a>z_value<span class="sc">^</span><span class="dv">2</span></span></code></pre></div>
<div class="exercise">
<p><span id="exr:unlabeled-div-56" class="exercise"><strong>Uppgift 3.14  (Test för proportionen oavgjorda) </strong></span>Samma gamla bollkunskap säger att 20 procent av matcher blir oavgjorda. I datan är 518 av 2750 matcher oavgjorda. Ställ upp hypoteser och fyll i koden nedan för att testa om bollkunskapen stämmer. Beräkna också z-värdet för hand.</p>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb152-1" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="at">x =</span> ___, <span class="at">n =</span> ___, <span class="at">p =</span> ___, <span class="at">correct =</span> F)</span></code></pre></div>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-57" class="exercise"><strong>Uppgift 3.15  (Test för proportionen hemmasegrar) </strong></span>Slutligen är då resten av matcherna, 1285 av 2750, hemmasegrar. Gammal bollkunskap säger: <em>47 procent av alla matcher är hemmasegrar</em>. Genomför ett z-test för att testa det påstående.</p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb153-1" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="at">x =</span> ___, <span class="at">n =</span> ___, <span class="at">p =</span> ___, <span class="at">correct =</span> F)</span></code></pre></div>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-58" class="exercise"><strong>Uppgift 3.16  (Population och stickprov) </strong></span>Ett hypotestest bygger på en underliggande tanke med en population (med någon för oss okänd proportion positiva utfall) och ett stickprov (i vilket vi kan observera andelen positiva utfall). Det är inte alltid uppenbart vad som egentligen är populationen. I fallet med fotbollsdatan, vad kan ses som populationen? Hur långt skulle man kunna generalisera de slutsatser man kan dra från datan?</p>
</div>
<p>Hypotestestet för proportioner som används här, <em>z-testet</em>, bygger på en normalapproximation av en binomialfördelning. Approximation blir bättre när antalet observationer är stort och nollhypotesens värde p0 ligger nära 0.5. En vanlig tumregel för när approximationen är giltig är att n gånger <span class="math inline">\(p_0\)</span> gånger <span class="math inline">\((1 - p_0)\)</span> ska vara större än 10.</p>
</div>
<div id="konfidensintervall-för-proportioner" class="section level2 hasAnchor" number="3.11">
<h2><span class="header-section-number">3.11</span> Konfidensintervall för proportioner<a href="#konfidensintervall-f%C3%B6r-proportioner" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Konstruktionen av ett konfidensintervall för en proportion är ganska lik konstruktionen för ett medelvärde. För en skattad proportion p och antal observationer n kan man beräkna p plus/minus ett z-värde från tabell gånger medelfelet, där medelfelet ges av roten ur <span class="math inline">\(p \cdot (1 - p) / n\)</span>. För exemplet med bortasegrar i allsvenskan är <span class="math inline">\(p = 0.344\)</span> och <span class="math inline">\(n = 2750\)</span>. Tabellvärdet hämtas från en tabell över kvantiler. För ett 95-procentigt konfidensintervall tar vi kvantilen 0.975 (2.5 procent i respektive svans) vilket ger värdet 1.96. Konfidensintervallet ges av</p>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb154-1" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">947</span> <span class="sc">+</span> <span class="dv">1803</span></span>
<span id="cb154-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb154-2" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="dv">947</span> <span class="sc">/</span> n</span>
<span id="cb154-3"><a href="ett-stickprov-av-normalfördelad-data.html#cb154-3" tabindex="-1"></a></span>
<span id="cb154-4"><a href="ett-stickprov-av-normalfördelad-data.html#cb154-4" tabindex="-1"></a>p <span class="sc">-</span> <span class="fl">1.96</span> <span class="sc">*</span> <span class="fu">sqrt</span>(p <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p) <span class="sc">/</span> n)</span>
<span id="cb154-5"><a href="ett-stickprov-av-normalfördelad-data.html#cb154-5" tabindex="-1"></a>p <span class="sc">+</span> <span class="fl">1.96</span> <span class="sc">*</span> <span class="fu">sqrt</span>(p <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p) <span class="sc">/</span> n)</span></code></pre></div>
<p>Notera att 0.33, det värde som var nollhypotesen i det tidigare testet, <em>ingår</em> i intervallet. Om man tittar på utskriften från <code>prop.test()</code> kan man se ett konfidensintervall. Det intervallet är dock inte beräknat på samma sätt den formel som förekommer på föreläsningarna. För att få matchande utskrift kan vi använda paketet <code>binom</code> och funktionen <code>binom.asymp()</code>.</p>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb155-1" tabindex="-1"></a><span class="co">#install.packages(&quot;binom&quot;)</span></span>
<span id="cb155-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb155-2" tabindex="-1"></a><span class="fu">library</span>(binom)</span>
<span id="cb155-3"><a href="ett-stickprov-av-normalfördelad-data.html#cb155-3" tabindex="-1"></a><span class="fu">binom.asymp</span>(<span class="at">x =</span> <span class="dv">947</span>, <span class="at">n =</span> <span class="dv">2750</span>)</span></code></pre></div>
<div class="exercise">
<p><span id="exr:unlabeled-div-59" class="exercise"><strong>Uppgift 3.17  (99-procentigt konfidensintervall) </strong></span>Gör lämplig ändring i koden nedan för att beräkna ett 99-procentigt konfidensintervall för andelen bortasegrar.</p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb156-1" tabindex="-1"></a><span class="fu">binom.asymp</span>(<span class="at">x =</span> <span class="dv">947</span>, <span class="at">n =</span> <span class="dv">2750</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code></pre></div>
</div>
</div>
<div id="chi-två-test-för-goodness-of-fit" class="section level2 hasAnchor" number="3.12">
<h2><span class="header-section-number">3.12</span> Chi-två-test för goodness-of-fit<a href="#chi-tv%C3%A5-test-f%C3%B6r-goodness-of-fit" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Ett proportionstest kan ses som ett test av en variabel med två möjliga klasser som utfall. Ett <em>goodness-of-fit</em>-test utvecklar det till valfritt antal klasser. Testet utförs som ett chi-två-test genom att beräkna ett observerat antal O och ett förväntat antal E för varje klass. Testvärdet ges av att man beräknar <span class="math inline">\((O - E)^2 / E\)</span> för varje klass och sedan summerar. Testfunktionen är en chi-två-fördelning där antalet frihetsgrader beror på antalet klasser.</p>
<p>Låt oss göra ett exempel baserat på fotbollsdatan. Där hade vi utfallet 947, 518 och 1285 för bortaseger, oavgjort och hemmaseger. Klassisk bollkunskap ger oss sannolikheterna 33, 20 och 47 procent. Testets hypoteser ges av</p>
<p><span class="math inline">\(H_0\)</span>: sannolikheterna för de olika utfallet ges av 33, 20 respektive 47 procent</p>
<p><span class="math inline">\(H_1\)</span>: minst något utfall har en annan sannolikhet än 33, 20 respektive 47 procent</p>
<p>För att få de förväntade värdena E multipliceras nollhypotesens sannolikheter med det totala antalet matcher.</p>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb157-1" tabindex="-1"></a>O <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">947</span>, <span class="dv">518</span>, <span class="dv">1285</span>)</span>
<span id="cb157-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb157-2" tabindex="-1"></a>E <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.33</span>,<span class="fl">0.20</span>,<span class="fl">0.47</span>) <span class="sc">*</span> <span class="dv">2750</span></span></code></pre></div>
<div class="exercise">
<p><span id="exr:unlabeled-div-60" class="exercise"><strong>Uppgift 3.18  (Granska E) </strong></span>Skriv ut objektet <code>E</code> och jämför med de observerade värdena. Notera att de förväntade värdena inte måste vara heltal, trots att de observerade värdena förstås alltid kommer vara det.</p>
</div>
<p>Testvärdet beräknas genom formeln för varje term följt av summan.</p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb158-1" tabindex="-1"></a>chisq_value <span class="ot">&lt;-</span> <span class="fu">sum</span>((O <span class="sc">-</span> E)<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> E)</span></code></pre></div>
<p>P-värdet beräknas från en chi-två-fördelning. Antalet frihetsgrader ges av antalet klasser minus antalet skattade parametrar minus ett. I det här fallet har inga parametrar skattats från datan så antalet frihetsgrader blir två. Ett chi-två-test beräknas med kvadrater så vi är enbart intresserade av högra svansen.</p>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb159-1" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb159-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb159-2" tabindex="-1"></a>  <span class="fu">geom_function</span>(<span class="at">fun =</span> dchisq, <span class="at">args =</span> <span class="fu">list</span>(<span class="at">df =</span> <span class="dv">2</span>)) <span class="sc">+</span></span>
<span id="cb159-3"><a href="ett-stickprov-av-normalfördelad-data.html#cb159-3" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> chisq_value) <span class="sc">+</span></span>
<span id="cb159-4"><a href="ett-stickprov-av-normalfördelad-data.html#cb159-4" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>,<span class="dv">10</span>)</span></code></pre></div>
<p>Man kan också beräkna ytan i svansen med <code>pchisq()</code>. Ett minus det resultatet ger den övre delen.</p>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb160-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb160-1" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pchisq</span>(chisq_value, <span class="at">df =</span> <span class="dv">2</span>)</span></code></pre></div>
<p>P-värdet är alltså 0.16, över den klassiska signifikansnivån på 5 procent, vilket ger att vi inte kan förkasta nollhypotesen. Om man gör ett chi-två-test för hand jämför man det observerade chi-två-värdet med ett tabellvärde över kvantiler. Tabellvärdet kan också hämtas med funktionen <code>qchisq()</code>, i det här fallet</p>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb161-1" tabindex="-1"></a><span class="fu">qchisq</span>(<span class="fl">0.95</span>, <span class="at">df =</span> <span class="dv">2</span>)</span></code></pre></div>
<p>Notera att man tar 0.95 eftersom man alltid tittar på den yttre svansen i ett chi-två-test.</p>
<p>R har en inbyggd funktion för chi-två-test. Dess argument ges av observerade antal och sannolikheter.</p>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb162-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb162-1" tabindex="-1"></a><span class="fu">chisq.test</span>(O, <span class="at">p =</span> <span class="fu">c</span>(<span class="fl">0.33</span>, <span class="fl">0.2</span>, <span class="fl">0.47</span>))</span></code></pre></div>
<p>Testet ger samma chi-två-värde och p-värde som beräknats ovan.</p>
<p>Situationen med flera klasser kan som sagt ses som en generalisering av fallet med två klasser. Det är alltså logiskt att chi-två-test kan användas även när man har två klasser. Följande exempel ger samma test som vi sett tidigare av andelen bortasegrar.</p>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb163-1" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">947</span>, <span class="dv">1803</span>), <span class="at">p =</span> <span class="fu">c</span>(<span class="fl">0.33</span>, <span class="fl">0.67</span>), <span class="at">correct =</span> F)</span></code></pre></div>
<p>Likt <code>prop.test()</code> sätter vi <code>correct</code> till <code>FALSE</code> för att inte göra en korrektion. Notera att <code>x</code> här anges som positiva och negativa utfall istället för positiva utfall och totalt antal utfall, vilket var fallet i <code>prop.test()</code>.</p>
<p>Chi-två-testet bygger på en underliggande normal-liknande approximation. En vanlig tumregel är att alla förväntade värden ska vara större än 5. R ger en varning om så inte är fallet.</p>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb164-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb164-1" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="fu">c</span>(<span class="dv">6</span>,<span class="dv">4</span>), <span class="at">p =</span> <span class="fu">c</span>(<span class="fl">0.51</span>, <span class="fl">0.49</span>))</span></code></pre></div>
<div class="exercise">
<p><span id="exr:unlabeled-div-61" class="exercise"><strong>Uppgift 3.19  (Chi-två med lika sannolikheter) </strong></span>En vanlig tillämpning av goodness-of-fit-testet är för att testa om alla klasser är lika sannolika. En jämn fördelning är grundinställning i <code>chisq.test()</code> så i det fallet behöver man bara ange de observerade värdena. En datainsamling om M&amp;M-godis gav följande antal.</p>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb165-1" tabindex="-1"></a>dat_mnm <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Color =</span> <span class="fu">c</span>(<span class="st">&quot;blue&quot;</span>, <span class="st">&quot;brown&quot;</span>, <span class="st">&quot;green&quot;</span>, </span>
<span id="cb165-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb165-2" tabindex="-1"></a>                                <span class="st">&quot;orange&quot;</span>, <span class="st">&quot;red&quot;</span>, <span class="st">&quot;yellow&quot;</span>),</span>
<span id="cb165-3"><a href="ett-stickprov-av-normalfördelad-data.html#cb165-3" tabindex="-1"></a>                      <span class="at">Count =</span> <span class="fu">c</span>(<span class="dv">180</span>, <span class="dv">80</span>, <span class="dv">88</span>, <span class="dv">160</span>, <span class="dv">134</span>, <span class="dv">166</span>))</span>
<span id="cb165-4"><a href="ett-stickprov-av-normalfördelad-data.html#cb165-4" tabindex="-1"></a></span>
<span id="cb165-5"><a href="ett-stickprov-av-normalfördelad-data.html#cb165-5" tabindex="-1"></a><span class="fu">ggplot</span>(dat_mnm, <span class="fu">aes</span>(Color, Count, <span class="at">fill =</span> Color)) <span class="sc">+</span></span>
<span id="cb165-6"><a href="ett-stickprov-av-normalfördelad-data.html#cb165-6" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb165-7"><a href="ett-stickprov-av-normalfördelad-data.html#cb165-7" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> dat_mnm<span class="sc">$</span>Color)</span></code></pre></div>
<p>Använd de observerade värdena i kolumnen <code>Count</code> för att testa om alla godisfärger är lika vanliga.</p>
</div>
</div>
<div id="bonus.-interaktiva-kartor-med-leaflet" class="section level2 hasAnchor" number="3.13">
<h2><span class="header-section-number">3.13</span> Bonus. Interaktiva kartor med leaflet<a href="ett-stickprov-av-normalfördelad-data.html#bonus.-interaktiva-kartor-med-leaflet" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Paketet <code>leaflet</code> (<a href="https://rstudio.github.io/leaflet/" class="uri">https://rstudio.github.io/leaflet/</a>) kopplar R till leaflet - ett verktyg för interaktiva kartor som ofta använd för kartor online.</p>
<div class="exercise">
<p><span id="exr:unlabeled-div-62" class="exercise"><strong>Uppgift 3.20  (Installera leaflet) </strong></span>Installera och ladda `leaflet genom att fylla i och köra raden nedan.</p>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb166-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb166-1" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;leaflet&quot;</span>)</span>
<span id="cb166-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb166-2" tabindex="-1"></a><span class="fu">library</span>(leaflet)</span></code></pre></div>
</div>
<p>Som en första kontroll kan vi köra den exempelkod som ges på hemsidan länkad till ovan.</p>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb167-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb167-1" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">leaflet</span>() <span class="sc">%&gt;%</span></span>
<span id="cb167-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb167-2" tabindex="-1"></a>  <span class="fu">addTiles</span>() <span class="sc">%&gt;%</span></span>
<span id="cb167-3"><a href="ett-stickprov-av-normalfördelad-data.html#cb167-3" tabindex="-1"></a>  <span class="fu">addMarkers</span>(<span class="at">lng =</span> <span class="fl">174.768</span>, <span class="at">lat =</span> <span class="sc">-</span><span class="fl">36.852</span>, </span>
<span id="cb167-4"><a href="ett-stickprov-av-normalfördelad-data.html#cb167-4" tabindex="-1"></a>             <span class="at">popup=</span><span class="st">&quot;The birthplace of R&quot;</span>)</span>
<span id="cb167-5"><a href="ett-stickprov-av-normalfördelad-data.html#cb167-5" tabindex="-1"></a>m</span></code></pre></div>
<p>På canvassidan finns en excelfil med data tillgänglig på Artportalen - <em>Artportalen, feromoninventering, 2011-2013.xlsx</em>. Datan kommer från från ett inventeringsprojekt vid SLU.</p>
<div class="exercise">
<p><span id="exr:unlabeled-div-63" class="exercise"><strong>Uppgift 3.21  (Importera datan) </strong></span>Ladda ner excelfilen och läs in datan med <code>read_excel()</code> från paketet <code>readxl</code>.</p>
<div class="sourceCode" id="cb168"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb168-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb168-1" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb168-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb168-2" tabindex="-1"></a>dat_leaf <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">&quot;___&quot;</span>)</span></code></pre></div>
</div>
<p>Kartans utseende kan ändras genom att ange en källa och karttyp. Tillgängliga alternativ kan skrivas ut med <code>providers</code>.</p>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb169-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb169-1" tabindex="-1"></a><span class="fu">leaflet</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb169-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb169-2" tabindex="-1"></a>  <span class="fu">addTiles</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb169-3"><a href="ett-stickprov-av-normalfördelad-data.html#cb169-3" tabindex="-1"></a>  <span class="fu">addProviderTiles</span>(providers<span class="sc">$</span>Stamen.Toner)</span></code></pre></div>
<div class="exercise">
<p><span id="exr:unlabeled-div-64" class="exercise"><strong>Uppgift 3.22  (Baskarta) </strong></span>Skriv ut tillgängliga baskartor med <code>providers</code>. Välj ett alternativ slumpmässigt och ändra koden ovan för att se hur det ser ut.</p>
</div>
<p>För att lägga till datapunkter kan man använda <code>addCircleMarkers()</code>.</p>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb170-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb170-1" tabindex="-1"></a><span class="fu">leaflet</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb170-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb170-2" tabindex="-1"></a>  <span class="fu">addTiles</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb170-3"><a href="ett-stickprov-av-normalfördelad-data.html#cb170-3" tabindex="-1"></a>  <span class="fu">addCircleMarkers</span>(<span class="at">lng =</span> dat_leaf<span class="sc">$</span>lng, </span>
<span id="cb170-4"><a href="ett-stickprov-av-normalfördelad-data.html#cb170-4" tabindex="-1"></a>                   <span class="at">lat =</span> dat_leaf<span class="sc">$</span>lat, <span class="at">radius =</span> <span class="dv">10</span>)</span></code></pre></div>
<div class="exercise">
<p><span id="exr:unlabeled-div-65" class="exercise"><strong>Uppgift 3.23  (Cirkelstorlek) </strong></span>Ändra storleken på cirklarna från <code>addCircleMarkers()</code> genom argumentet <code>radius</code>.</p>
</div>
<p>Slutligen kan vi lägga till en etikett för år med argumentet <code>popup</code>. Texten kommer upp när man klickar på en punkt.</p>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb171-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb171-1" tabindex="-1"></a><span class="fu">leaflet</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb171-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb171-2" tabindex="-1"></a>  <span class="fu">addTiles</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb171-3"><a href="ett-stickprov-av-normalfördelad-data.html#cb171-3" tabindex="-1"></a>  <span class="fu">addCircleMarkers</span>(<span class="at">lng =</span> dat_leaf<span class="sc">$</span>lng, </span>
<span id="cb171-4"><a href="ett-stickprov-av-normalfördelad-data.html#cb171-4" tabindex="-1"></a>                   <span class="at">lat =</span> dat_leaf<span class="sc">$</span>lat, <span class="at">radius =</span> <span class="dv">10</span>, </span>
<span id="cb171-5"><a href="ett-stickprov-av-normalfördelad-data.html#cb171-5" tabindex="-1"></a>                   <span class="at">popup =</span> dat_leaf<span class="sc">$</span>Rödlistade)</span></code></pre></div>
<div class="exercise">
<p><span id="exr:unlabeled-div-66" class="exercise"><strong>Uppgift 3.24  (Artnamn) </strong></span>Ändra i koden ovan för att ange artnamn som popup-text istället för rödlistestatus. Funktionen <code>paste()</code> kan också vara intressant för att ta med mer information i texten: <code>paste(dat_leaf$Rödlistade, dat_leaf$Antal)</code> skulle exempelvis ge både status och antal individer vid den specifika observationen.</p>
</div>
</div>
<div id="test-för-två-stickprov" class="section level2 hasAnchor" number="3.14">
<h2><span class="header-section-number">3.14</span> Test för två stickprov<a href="#test-f%C3%B6r-tv%C3%A5-stickprov" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Datorövning 5 handlar om hypotestest och konfidensintervall för jämförelse av två stickprov. Efter övningen ska vi kunna genomföra och tolka</p>
<ul>
<li><p>t-test för jämförelse av två medelvärden,</p></li>
<li><p>z-test för jämförelse av två proportioner,</p></li>
<li><p>chi-två-test för jämförelse av fördelningar mellan två eller flera grupper,</p></li>
<li><p>konfidensintervall för skillnaden mellan två medelvärden eller två proportioner.</p></li>
</ul>
</div>
<div id="repetition-av-datorövning-4" class="section level2 hasAnchor" number="3.15">
<h2><span class="header-section-number">3.15</span> Repetition av datorövning 4<a href="#repetition-av-dator%C3%B6vning-4" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>När man startar en ny R-session bör man ladda de paket man vet kommer behövas med <code>library()</code>. Om paket inte finns installerade måste man först köra <code>install.packages()</code>.</p>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb172-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb172-1" tabindex="-1"></a><span class="co"># install.packages(&quot;tidyverse&quot;)</span></span>
<span id="cb172-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb172-2" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
<p>I datorövning 4 tittade vi på tester som inte bygger på normalfördelning: dels tester för proportioner, där varje observation är något av två möjliga utfall; dels tester för kategoridata, där varje observation har ett ufall i någon av flera kategorier.</p>
<p>Proportioner kan testas med ett z-test. Säg att man testar om en doft har en effekt på en insekt, man skickar 20 insekter i ett y-rör och 16 går mot doften. Hypoteserna ges av</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: proportionen i populationen är 0.5,</li>
<li><span class="math inline">\(H_1\)</span>: proportionen i populationen är inte 0.5.</li>
</ul>
<p>I R genomförs ett z-test med <code>prop.test()</code>. Funktionen gör en korrektion som ger ett något bättre test än det man ofta beräknar för hand. Korrektionen kan sättas av med argumentet <code>correct</code>.</p>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb173-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb173-1" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="at">x =</span> <span class="dv">16</span>, <span class="at">n =</span> <span class="dv">20</span>, <span class="at">p =</span> <span class="fl">0.5</span>, <span class="at">correct =</span> F)</span></code></pre></div>
<p>Ett lågt p-värde tyder på en signifikant skillnad från 0.5.</p>
<p>För att få samma konfidensintervall som det man beräknar för hand kan man använda <code>binom.asymp()</code> från paketet <code>binom</code>.</p>
<div class="sourceCode" id="cb174"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb174-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb174-1" tabindex="-1"></a><span class="fu">library</span>(binom)</span>
<span id="cb174-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb174-2" tabindex="-1"></a><span class="fu">binom.asymp</span>(<span class="dv">16</span>, <span class="dv">20</span>)</span></code></pre></div>
<p>Populationens proportion ligger med 95 procents konfidens mellan 0.62 och 0.98.</p>
<p>Om utfallen är mer än två kategorier kan en hypotes om datans fördelning testas med ett goodness-of-fit-test, vilket är ett slags chi-två-test. Testet bygger på att observerade antal (O) ställs mot förväntade antal (E). I R genomförs ett chi-två-test med <code>chisq.test()</code>. Säg som exempel att man studerar fågelpopulationer genom en observationsstudie. Observerade antal av fyra fågelarter är 102, 53, 75 och 12 och de förväntade andelarna av arterna är 50, 15, 25 och 10 procent. Testets hypoteser ges av</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: proportionerna följer den förväntade fördelningen,</li>
<li><span class="math inline">\(H_1\)</span>: proportionerna följer inte den förväntade fördelningen,</li>
</ul>
<p>och testet ges av</p>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb175-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb175-1" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="fu">c</span>(<span class="dv">102</span>, <span class="dv">53</span>, <span class="dv">75</span>, <span class="dv">12</span>), <span class="at">p =</span> <span class="fu">c</span>(<span class="fl">0.5</span>, <span class="fl">0.15</span>, <span class="fl">0.25</span>, <span class="fl">0.10</span>))</span></code></pre></div>
<p>Ett lågt p-värde tyder på att de antagna proportionerna inte stämmer. Antalet frihetsgrader ges i ett chi-två-test av antalet klasser minus antalet skattade parametrar minus ett. I det här fallet finns fyra klasser och ingen skattad parameter.</p>
</div>
<div id="två-stickprov-och-normalfördelad-data" class="section level2 hasAnchor" number="3.16">
<h2><span class="header-section-number">3.16</span> Två stickprov och normalfördelad data<a href="#tv%C3%A5-stickprov-och-normalf%C3%B6rdelad-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Vid normalfördelad data från två stickprov eller grupper vill vi nästan alltid testa om populationerna har samma medelvärde. Det kan också ses som att vi testar om differensen mellan medelvärdena är noll. Vi skiljer mellan två fall: <em>matchade stickprov</em> - där varje observation i den ena gruppen är <em>kopplad</em> till en observation i den andra gruppen; och <em>oberoende stickprov</em> - där det inte finns någon sådan koppling mellan stickproven. Typiska exempel på matchade stickprov är när man mäter samma individ för och efter en behandling och syskonstudier där ett syskon får en behandling och den andra en annan behandling.</p>
<div id="t-test-för-två-matchade-stickprov" class="section level3 hasAnchor" number="3.16.1">
<h3><span class="header-section-number">3.16.1</span> t-test för två matchade stickprov<a href="#t-test-f%C3%B6r-tv%C3%A5-matchade-stickprov" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Vid matchade stickprov kan varje observation i en behandlingsgrupp paras med en observation i den andra gruppen. Själva testet är ett t-test för <em>ett</em> stickprov på differensserien beräknat från varje par. I R kan man antingen beräkna den differensserien eller använda <code>t.test()</code> med två dataserier och argumentet för parvisa observationer satt till sant, <code>paired = T</code>.
Som exempel ges följande data från en studie på äpple, där trädhöjd mätts före och efter en näringsbehandling.</p>
<div class="sourceCode" id="cb176"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb176-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb176-1" tabindex="-1"></a>dat_apple <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">Tree =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>, </span>
<span id="cb176-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb176-2" tabindex="-1"></a>              <span class="at">Before =</span> <span class="fu">c</span>(<span class="dv">48</span>, <span class="dv">43</span>, <span class="dv">30</span>, <span class="dv">47</span>), </span>
<span id="cb176-3"><a href="ett-stickprov-av-normalfördelad-data.html#cb176-3" tabindex="-1"></a>              <span class="at">After =</span> <span class="fu">c</span>(<span class="dv">51</span>, <span class="dv">44</span>, <span class="dv">42</span>, <span class="dv">54</span>))</span>
<span id="cb176-4"><a href="ett-stickprov-av-normalfördelad-data.html#cb176-4" tabindex="-1"></a>dat_apple</span></code></pre></div>
<p>Datan kan illustreras med ett punktdiagram där en linje binder samman paret. För att enkelt skapa grafen i <code>ggplot2</code> kan man först omstrukturera datan till lång form genom <code>pivot_longer</code>.</p>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb177-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb177-1" tabindex="-1"></a>dat_long <span class="ot">&lt;-</span> dat_apple <span class="sc">%&gt;%</span> </span>
<span id="cb177-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb177-2" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="sc">-</span>Tree, <span class="at">names_to =</span> <span class="st">&quot;Time&quot;</span>, <span class="at">values_to =</span> <span class="st">&quot;Height&quot;</span>)</span>
<span id="cb177-3"><a href="ett-stickprov-av-normalfördelad-data.html#cb177-3" tabindex="-1"></a>dat_long</span></code></pre></div>
<div class="exercise">
<p><span id="exr:unlabeled-div-67" class="exercise"><strong>Uppgift 3.25  (Äppelgraf) </strong></span>Fyll i kodstycket nedan för en graf av äppeldatan. Axlarna ges av <code>Time</code> och <code>Height</code>. Två observationer kan kopplas genom att sätta <code>Tree</code> som grupp.</p>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb178-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb178-1" tabindex="-1"></a><span class="fu">ggplot</span>(dat_long, <span class="fu">aes</span>(___, ___, <span class="at">group =</span> ___)) <span class="sc">+</span></span>
<span id="cb178-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb178-2" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb178-3"><a href="ett-stickprov-av-normalfördelad-data.html#cb178-3" tabindex="-1"></a>  <span class="fu">geom_line</span>()</span></code></pre></div>
</div>
<p>För att testa för skillnad före och efter behandling sätter vi upp hypoteser</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu\)</span> före behandling är lika med <span class="math inline">\(\mu\)</span> efter behandling</li>
<li><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\mu\)</span> före behandling är skild från <span class="math inline">\(\mu\)</span> efter behandling</li>
</ul>
<p>Testet kan antingen utföras som ett enkelt t-test på differensserien</p>
<div class="sourceCode" id="cb179"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb179-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb179-1" tabindex="-1"></a><span class="fu">t.test</span>(dat_apple<span class="sc">$</span>Before <span class="sc">-</span> dat_apple<span class="sc">$</span>After)</span></code></pre></div>
<p>eller som ett t-test för två stickprov där man särskilt anger att datan är parad</p>
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb180-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb180-1" tabindex="-1"></a><span class="fu">t.test</span>(dat_apple<span class="sc">$</span>Before, dat_apple<span class="sc">$</span>After, <span class="at">paired =</span> T)</span></code></pre></div>
<p>För bägge alternativen måste datan vara ordnad så att de två vektorerna matchar varandra parvis. Ett p-värde på <span class="math inline">\(0.0987\)</span> ger att man inte förkastar vid en signifikansnivå på fem procent. Vi drar därmed slutsatsen att det inte finns någon signifikant skillnad före och efter behandling.</p>
<div class="exercise">
<p><span id="exr:unlabeled-div-68" class="exercise"><strong>Uppgift 3.26  (Ensidigt test) </strong></span>Gör ett tillägg till ett av kodstyckena med <code>t.test()</code> för att beräkna ett ensidigt test med mothypotesen att träden ökar i höjd efter behandling. Hjälpsidan för <code>t.test()</code> kan tas fram genom att köra <code>?t.test()</code>.</p>
</div>
<p>Konfidensintervallet beräknas från differenserna på samma sätt som vid ett stickprov med normalfördelad data. Tolkningen liknar den för ett stickprov: med 95 procents konfidens ligger den sanna skillnaden i medelvärden i intervallet.</p>
</div>
<div id="t-test-för-två-oberoende-stickprov" class="section level3 hasAnchor" number="3.16.2">
<h3><span class="header-section-number">3.16.2</span> t-test för två oberoende stickprov<a href="#t-test-f%C3%B6r-tv%C3%A5-oberoende-stickprov" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Ett t-test för två oberoende stickprov testar om två populationsmedelvärden är lika. Ta som exempel följande data på jordgubbsskörd vid två olika näringsbehandlingar (A och B). Här är stickproven inte matchade - det finns <strong>ingen</strong> direkt koppling mellan en observation i den ena behandlingsgruppen till någon observation i den andra.</p>
<div class="sourceCode" id="cb181"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb181-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb181-1" tabindex="-1"></a>dat_berry <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Behandling =</span> <span class="fu">c</span>(<span class="st">&quot;A&quot;</span>, <span class="st">&quot;A&quot;</span>, <span class="st">&quot;A&quot;</span>, <span class="st">&quot;A&quot;</span>, </span>
<span id="cb181-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb181-2" tabindex="-1"></a>                                       <span class="st">&quot;B&quot;</span>, <span class="st">&quot;B&quot;</span>, <span class="st">&quot;B&quot;</span>, <span class="st">&quot;B&quot;</span>),</span>
<span id="cb181-3"><a href="ett-stickprov-av-normalfördelad-data.html#cb181-3" tabindex="-1"></a>                        <span class="at">Vikt =</span> <span class="fu">c</span>(<span class="dv">40</span>, <span class="fl">48.2</span>, <span class="fl">39.2</span>, <span class="fl">47.9</span>, </span>
<span id="cb181-4"><a href="ett-stickprov-av-normalfördelad-data.html#cb181-4" tabindex="-1"></a>                                 <span class="fl">57.5</span>, <span class="fl">61.5</span>, <span class="dv">58</span>, <span class="fl">66.5</span>))</span>
<span id="cb181-5"><a href="ett-stickprov-av-normalfördelad-data.html#cb181-5" tabindex="-1"></a>dat_berry</span></code></pre></div>
<p>Datan kan illustreras med ett enkelt punktdiagram.</p>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb182-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb182-1" tabindex="-1"></a><span class="fu">ggplot</span>(dat_berry, <span class="fu">aes</span>(Behandling, Vikt)) <span class="sc">+</span></span>
<span id="cb182-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb182-2" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code></pre></div>
<p>Ett t-test för två oberoende stickprov har nollhypotesen att grupperna har samma populationsmedelvärde och alternativhypotesen att populationsmedelvärdena är skilda (för det tvåsidiga fallet):</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu_A\)</span> är lika med <span class="math inline">\(\mu_B\)</span></li>
<li><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\mu_A\)</span> är ej lika med <span class="math inline">\(\mu_B\)</span></li>
</ul>
<p>Testet kan utföras i R genom funktionen <code>t.test()</code>. Data kan antingen anges som en formel med dess data <code>Vikt ~ Behandling, data = dat_berry</code> (vilket man kan läsa som <em>vikt uppdelat efter behandling</em>) eller som två skilda vektorer. Det förra alternativet är oftast enklare om man har datan på lång form - med en kolumn som anger grupp (i exemplet <em>Behandling</em>) och en kolumn som anger utfallsvärdet (i exemplet <em>Vikt</em>).</p>
<p>För formen med formel ger det</p>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb183-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb183-1" tabindex="-1"></a><span class="co"># Formelskrivning</span></span>
<span id="cb183-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb183-2" tabindex="-1"></a><span class="fu">t.test</span>(Vikt <span class="sc">~</span> Behandling, <span class="at">data =</span> dat_berry, <span class="at">var.equal =</span> T)</span></code></pre></div>
<p>och för formen med vektorer</p>
<div class="sourceCode" id="cb184"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb184-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb184-1" tabindex="-1"></a><span class="co"># Två separata vektorer</span></span>
<span id="cb184-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb184-2" tabindex="-1"></a><span class="do">## Filtrera ut data där behandling är A</span></span>
<span id="cb184-3"><a href="ett-stickprov-av-normalfördelad-data.html#cb184-3" tabindex="-1"></a>Vikt_A <span class="ot">&lt;-</span> dat_berry<span class="sc">$</span>Vikt[dat_berry<span class="sc">$</span>Behandling <span class="sc">==</span> <span class="st">&quot;A&quot;</span>]</span>
<span id="cb184-4"><a href="ett-stickprov-av-normalfördelad-data.html#cb184-4" tabindex="-1"></a></span>
<span id="cb184-5"><a href="ett-stickprov-av-normalfördelad-data.html#cb184-5" tabindex="-1"></a><span class="do">## Filtrera ut data där behandling är B</span></span>
<span id="cb184-6"><a href="ett-stickprov-av-normalfördelad-data.html#cb184-6" tabindex="-1"></a>Vikt_B <span class="ot">&lt;-</span> dat_berry<span class="sc">$</span>Vikt[dat_berry<span class="sc">$</span>Behandling <span class="sc">==</span> <span class="st">&quot;B&quot;</span>]</span>
<span id="cb184-7"><a href="ett-stickprov-av-normalfördelad-data.html#cb184-7" tabindex="-1"></a></span>
<span id="cb184-8"><a href="ett-stickprov-av-normalfördelad-data.html#cb184-8" tabindex="-1"></a><span class="fu">t.test</span>(Vikt_A, Vikt_B, <span class="at">var.equal =</span> T)</span></code></pre></div>
<p>Argumentet <code>var.equal = T</code> används för att beräkna testet där gruppernas varianser antas vara lika. Grundinställningen är testet där varianser inte antas vara lika, så <code>t.test(Vikt ~ Behandling, data = dat)</code> ger ett lite annat resultat.</p>
<div class="exercise">
<p><span id="exr:unlabeled-div-69" class="exercise"><strong>Uppgift 3.27  (Ej lika varianser) </strong></span>Vilka resultatvärden ändras i utskriften om man sätter <code>var.equal = F</code>?</p>
</div>
<p>Testet ger ett p-värde på <span class="math inline">\(0.0018\)</span>, vilket leder till att nollhypotesen förkastas på enprocentsnivån. Detta tyder på att det finns en viktskillnad mellan behandlingarna. Utskriften ger också ett 95-procentigt konfidensintervall på <span class="math inline">\((-24.898, -9.202)\)</span>. Tolkningen är att <em>skillnaden</em> mellan populationsmedelvärden ligger i intervallet med 95 procents konfidens. Notera att värdet noll inte ligger i intervallet.</p>
<p>Om man har fler än två grupper kan man vilja göra parvisa t-test - alltså ett t-test för varje par av grupper.
Ett exempel på funktionen <code>pairwise.t.test()</code> ges nedan. Funktionen bygger på att datan är i <em>lång</em> form, med en kolumn som anger det numeriska utfallet och en kolumn som anger behandlingen.</p>
<div class="sourceCode" id="cb185"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb185-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb185-1" tabindex="-1"></a><span class="fu">pairwise.t.test</span>(dat_berry<span class="sc">$</span>Vikt, dat_berry<span class="sc">$</span>Behandling, </span>
<span id="cb185-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb185-2" tabindex="-1"></a>                <span class="at">p.adjust.method =</span> <span class="st">&quot;none&quot;</span>, <span class="at">pool.sd =</span> F)</span></code></pre></div>
<pre><code>## 
##  Pairwise comparisons using t tests with non-pooled SD 
## 
## data:  dat_berry$Vikt and dat_berry$Behandling 
## 
##   A    
## B 0.002
## 
## P value adjustment method: none</code></pre>
<p><em>Matchade</em> observationer kan också kallas <em>parade</em> (eng. paired) så se upp med terminologin. Funktionen <code>pairwise.t.test()</code> för <em>parvisa jämförelse</em> mellan behandlingar, men testerna är t-test för oberoende stickprov.</p>
</div>
</div>
<div id="z-test-och-konfidensintervall-för-två-proportioner" class="section level2 hasAnchor" number="3.17">
<h2><span class="header-section-number">3.17</span> z-test och konfidensintervall för två proportioner<a href="#z-test-och-konfidensintervall-f%C3%B6r-tv%C3%A5-proportioner" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Om man vill jämföra två proportioner kan man använda z-testet för två stickprov. Säg till exempel att man har två sorter av någon planta och vill se hur stor proportion som är infekterad av bladmögel. I den ena gruppen (sort A) är 17 av 50 infektera och i den andra (sort B) är 26 av 60 infekterade. Testets hypoteser är i det tvåsidiga fallet</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: proportion A är lika med proportion B</li>
<li><span class="math inline">\(H_1\)</span>: proportion A är skild från proportion B</li>
</ul>
<p>I R kan testet genomföras med <code>prop.test()</code>-funktionen. Funktionens första argument är antalen infekterade, som en vektor med två värden, och dess andra argument är totalerna. Likt testet med ett stickprov finns en möjlighet att göra en kontinuitetskorrektion med <code>correct</code>-argumentet. För att få samma resultat som räkning för hand anger vi att korrektion inte ska göras med <code>correct = F</code>.</p>
<div class="sourceCode" id="cb187"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb187-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb187-1" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">17</span>, <span class="dv">26</span>), <span class="at">n =</span> <span class="fu">c</span>(<span class="dv">50</span>, <span class="dv">60</span>), <span class="at">correct =</span> F)</span></code></pre></div>
<p>Notera att funktionen inte ger ett z-värde utan ett <span class="math inline">\(\chi^2\)</span>-värde (utskrivet <code>X-squared</code>). Det beror på att funktionen beräknar z-testet som ett likvärdigt <span class="math inline">\(\chi^2\)</span>-test. Det z-värde man får om man genomför testet som ett z-test är detsamma som roten ur utskriftens <span class="math inline">\(\chi^2\)</span>-värde. Testet ger ett högt p-värde på 0.32 vilket innebär att nollhypotesen inte förkastas: det finns ingen signifikant skillnad i infektionsproportion.</p>
<p>Funktionen <code>prop.test()</code> ger också en utskrift av konfidensintervallet. Tolkning är att skillnaden i proportioner mellan populationerna ligger i intervallet med 95 procents konfidens. Notera att nollan ingår i intervallet.</p>
<div class="exercise">
<p><span id="exr:unlabeled-div-70" class="exercise"><strong>Uppgift 3.28  (Burfågel) </strong></span>Det finns en förvånansvärt stor mängd studier på kopplingen mellan innehav av burfågel och lungcancer. En sådan studie (Kohlmeier et al 1992) ger följande antal för burfågelägande och lungcancer.</p>
<div class="sourceCode" id="cb188"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb188-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb188-1" tabindex="-1"></a>dat_bird <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(Burfågel <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;Burfågel&quot;</span>, <span class="st">&quot;Ej_burfågel&quot;</span>),</span>
<span id="cb188-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb188-2" tabindex="-1"></a>              <span class="at">Lungcancer =</span> <span class="fu">c</span>(<span class="dv">98</span>, <span class="dv">141</span>),</span>
<span id="cb188-3"><a href="ett-stickprov-av-normalfördelad-data.html#cb188-3" tabindex="-1"></a>              <span class="at">Ej_lungcancer =</span> <span class="fu">c</span>(<span class="dv">101</span>, <span class="dv">328</span>))</span>
<span id="cb188-4"><a href="ett-stickprov-av-normalfördelad-data.html#cb188-4" tabindex="-1"></a>dat_bird</span></code></pre></div>
<p>Datan tyder på att människor med burfågel har en förhöjd risk att drabbas av lungcancer. Genomför ett z-test för att se om andelen burfågelägare än densamma i de två patientgrupperna.</p>
<div class="sourceCode" id="cb189"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb189-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb189-1" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="at">x =</span> <span class="fu">c</span>(___, ___), <span class="at">n =</span> <span class="fu">c</span>(___, ___), <span class="at">correct =</span> F)</span></code></pre></div>
</div>
</div>
<div id="chi-två-test-för-korstabeller" class="section level2 hasAnchor" number="3.18">
<h2><span class="header-section-number">3.18</span> Chi-två-test för korstabeller<a href="#chi-tv%C3%A5-test-f%C3%B6r-korstabeller" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Data med två kategoriska variabler kan presenteras med en korstabell. Ta som (ett något deppigt) exempel överlevnadsdata från Titanic. Datan finns tillgänglig i R som <code>Titanic</code>. I detta fall ges överlevnad filtrerad på vuxna män, uppdelat efter klass.</p>
<div class="sourceCode" id="cb190"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb190-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb190-1" tabindex="-1"></a>dat_titanic <span class="ot">&lt;-</span> Titanic <span class="sc">%&gt;%</span> </span>
<span id="cb190-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb190-2" tabindex="-1"></a>  <span class="fu">data.frame</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb190-3"><a href="ett-stickprov-av-normalfördelad-data.html#cb190-3" tabindex="-1"></a>  <span class="fu">filter</span>(Sex <span class="sc">==</span> <span class="st">&quot;Male&quot;</span>, Age <span class="sc">==</span> <span class="st">&quot;Adult&quot;</span>)</span>
<span id="cb190-4"><a href="ett-stickprov-av-normalfördelad-data.html#cb190-4" tabindex="-1"></a>dat_titanic</span></code></pre></div>
<p>En korstabell kan konstrueras med <code>pivot_wider</code>.</p>
<div class="sourceCode" id="cb191"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb191-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb191-1" tabindex="-1"></a>dat_wide <span class="ot">&lt;-</span> dat_titanic <span class="sc">%&gt;%</span> </span>
<span id="cb191-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb191-2" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> Survived, <span class="at">values_from =</span> Freq)</span>
<span id="cb191-3"><a href="ett-stickprov-av-normalfördelad-data.html#cb191-3" tabindex="-1"></a>dat_wide</span></code></pre></div>
<p>Datan tyder på att överlevnad är beroende av klass. Vi kan illustrera med uppdelade staplar.</p>
<div class="sourceCode" id="cb192"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb192-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb192-1" tabindex="-1"></a><span class="fu">ggplot</span>(dat_titanic, <span class="fu">aes</span>(Class, Freq, <span class="at">fill =</span> Survived)) <span class="sc">+</span></span>
<span id="cb192-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb192-2" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">position =</span> <span class="fu">position_fill</span>(), <span class="at">color =</span> <span class="st">&quot;black&quot;</span>) <span class="sc">+</span></span>
<span id="cb192-3"><a href="ett-stickprov-av-normalfördelad-data.html#cb192-3" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;red4&quot;</span>, <span class="st">&quot;white&quot;</span>))</span></code></pre></div>
<p>Argumentet <code>position</code> i <code>geom_bar</code> används för att skapa proportionella staplar.</p>
<p>Ett chi-två-test på en korstabell har nollhypotesen att det inte finns något samband mellan variabeln för rader och variabeln för kolumner. Chi-två-testet kan tillämpas på korstabeller med godtyckligt antal rader och kolumner. Antal frihetsgrader ges av antal rader minus ett gånger antal kolumner minus ett. Testet kan enkelt göras med <code>chisq.test()</code>. Som ingångsvärde kan man plocka ut kolumnerna med numeriska värden genom hakparenteser.</p>
<div class="sourceCode" id="cb193"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb193-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb193-1" tabindex="-1"></a>dat_wide[, <span class="dv">4</span><span class="sc">:</span><span class="dv">5</span>] <span class="co"># De två numeriska kolumnerna</span></span>
<span id="cb193-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb193-2" tabindex="-1"></a></span>
<span id="cb193-3"><a href="ett-stickprov-av-normalfördelad-data.html#cb193-3" tabindex="-1"></a><span class="fu">chisq.test</span>(dat_wide[, <span class="dv">4</span><span class="sc">:</span><span class="dv">5</span>])</span></code></pre></div>
<p>Utskriften ger teststorheten, antal frihetsgrader, och p-värdet. I det här fallet är p-värdet mycket litet och slutsatsen blir att nollhypotesen förkastas - det finns ett samband mellan klass och överlevnad. Antalet frihetsgrader ges av antalet rader minus ett gånger antalet kolumner minus ett (här <span class="math inline">\((4-1) \cdot (2-1) = 3\)</span>).</p>
<p>Chi-två-testet är ett asymptotiskt test - dess egenskaper är beroende av <em>stora</em> stickprov. Som gräns för storleken används ofta att samtliga förväntade antal ska vara större än 5. Funktionen ger en varning om förväntade värden är små. En möjlig lösning i sådana fall är att slå ihop klasser.</p>
<div class="sourceCode" id="cb194"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb194-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb194-1" tabindex="-1"></a>test_result <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(dat_wide[, <span class="dv">4</span><span class="sc">:</span><span class="dv">5</span>])</span>
<span id="cb194-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb194-2" tabindex="-1"></a>test_result<span class="sc">$</span>expected <span class="co"># Samtliga förväntade värden över 5</span></span></code></pre></div>
<p>Om detta krav inte är uppfyllt skriver funktionen ut en varning.</p>
<div class="exercise">
<p><span id="exr:unlabeled-div-71" class="exercise"><strong>Uppgift 3.29  (Ogiltig approximation) </strong></span>Ta följande lilla korstabell och kör <code>chisq.test()</code> för att få ett felmeddelande.</p>
<div class="sourceCode" id="cb195"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb195-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb195-1" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">4</span>,<span class="dv">2</span>,<span class="dv">5</span>,<span class="dv">1</span>), <span class="dv">2</span>)</span>
<span id="cb195-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb195-2" tabindex="-1"></a>dat</span></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]    4    5
## [2,]    2    1</code></pre>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-72" class="exercise"><strong>Uppgift 3.30  (Burfågeln återvänder) </strong></span>En svensk studie på koppling mellan burfågel och lungcancer (Modigh et al, 1996) ger följande antal (för män).</p>
<div class="sourceCode" id="cb197"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb197-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb197-1" tabindex="-1"></a>dat_bird_swe <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(Burfågel <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;Burfågel&quot;</span>, <span class="st">&quot;Ej_burfågel&quot;</span>),</span>
<span id="cb197-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb197-2" tabindex="-1"></a>              <span class="at">Lungcancer =</span> <span class="fu">c</span>(<span class="dv">108</span>, <span class="dv">144</span>),</span>
<span id="cb197-3"><a href="ett-stickprov-av-normalfördelad-data.html#cb197-3" tabindex="-1"></a>              <span class="at">Ej_lungcancer =</span> <span class="fu">c</span>(<span class="dv">171</span>, <span class="dv">256</span>))</span>
<span id="cb197-4"><a href="ett-stickprov-av-normalfördelad-data.html#cb197-4" tabindex="-1"></a>dat_bird_swe</span></code></pre></div>
<p>Genomför ett chi-två-test för att se om andelen cancerdrabbade än densamma i de två burfågelsgrupperna. Formulera tydliga hypoteser. För att få utfall som stämmer med en handräkning kan man sätta <code>correct = F</code>.</p>
<div class="sourceCode" id="cb198"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb198-1"><a href="ett-stickprov-av-normalfördelad-data.html#cb198-1" tabindex="-1"></a>dat_bird_swe[, <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>)]</span>
<span id="cb198-2"><a href="ett-stickprov-av-normalfördelad-data.html#cb198-2" tabindex="-1"></a><span class="fu">chisq.test</span>(___, <span class="at">correct =</span> F)</span></code></pre></div>
</div>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="beskrivande-statistik.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="variansanalys.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": false,
    "twitter": false,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": false
  },
  "fontsettings": {
    "theme": "white",
    "family": "serif",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["R-anvisningar.pdf"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
