<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>4 Ett stickprov av icke-normalfördelad data | R-anvisningar till Grundläggande statistik</title>
  <meta name="description" content="4 Ett stickprov av icke-normalfördelad data | R-anvisningar till Grundläggande statistik" />
  <meta name="generator" content="bookdown 0.40 and GitBook 2.6.7" />

  <meta property="og:title" content="4 Ett stickprov av icke-normalfördelad data | R-anvisningar till Grundläggande statistik" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="4 Ett stickprov av icke-normalfördelad data | R-anvisningar till Grundläggande statistik" />
  
  
  



<meta name="date" content="2024-10-06" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="ett-stickprov-av-normalfördelad-data.html"/>
<link rel="next" href="test-för-två-stickprov.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">R-anvisningar</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introduktion</a></li>
<li class="chapter" data-level="" data-path="installation-av-r-och-rstudio.html"><a href="installation-av-r-och-rstudio.html"><i class="fa fa-check"></i>Installation av R och RStudio</a>
<ul>
<li class="chapter" data-level="0.1" data-path="installation-av-r-och-rstudio.html"><a href="installation-av-r-och-rstudio.html#inledning"><i class="fa fa-check"></i><b>0.1</b> Inledning</a></li>
<li class="chapter" data-level="0.2" data-path="installation-av-r-och-rstudio.html"><a href="installation-av-r-och-rstudio.html#installation-av-r"><i class="fa fa-check"></i><b>0.2</b> Installation av R</a></li>
<li class="chapter" data-level="0.3" data-path="installation-av-r-och-rstudio.html"><a href="installation-av-r-och-rstudio.html#installation-av-rstudio"><i class="fa fa-check"></i><b>0.3</b> Installation av RStudio</a></li>
<li class="chapter" data-level="0.4" data-path="installation-av-r-och-rstudio.html"><a href="installation-av-r-och-rstudio.html#gränssnittet-i-rstudio"><i class="fa fa-check"></i><b>0.4</b> Gränssnittet i RStudio</a></li>
<li class="chapter" data-level="0.5" data-path="installation-av-r-och-rstudio.html"><a href="installation-av-r-och-rstudio.html#paket-i-r"><i class="fa fa-check"></i><b>0.5</b> Paket i R</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="datahantering-och-grafer.html"><a href="datahantering-och-grafer.html"><i class="fa fa-check"></i><b>1</b> Datahantering och grafer</a>
<ul>
<li class="chapter" data-level="1.1" data-path="datahantering-och-grafer.html"><a href="datahantering-och-grafer.html#uppstart-och-orientering"><i class="fa fa-check"></i><b>1.1</b> Uppstart och orientering</a></li>
<li class="chapter" data-level="1.2" data-path="datahantering-och-grafer.html"><a href="datahantering-och-grafer.html#packages-från-cran"><i class="fa fa-check"></i><b>1.2</b> <em>Packages</em> från CRAN</a></li>
<li class="chapter" data-level="1.3" data-path="datahantering-och-grafer.html"><a href="datahantering-och-grafer.html#objekt-och-funktioner"><i class="fa fa-check"></i><b>1.3</b> Objekt och funktioner</a></li>
<li class="chapter" data-level="1.4" data-path="datahantering-och-grafer.html"><a href="datahantering-och-grafer.html#sekvenser-av-funktioner"><i class="fa fa-check"></i><b>1.4</b> Sekvenser av funktioner</a></li>
<li class="chapter" data-level="1.5" data-path="datahantering-och-grafer.html"><a href="datahantering-och-grafer.html#datainskrivning"><i class="fa fa-check"></i><b>1.5</b> Datainskrivning</a></li>
<li class="chapter" data-level="1.6" data-path="datahantering-och-grafer.html"><a href="datahantering-och-grafer.html#urval-ur-en-tabell-med-select-och-filter"><i class="fa fa-check"></i><b>1.6</b> Urval ur en tabell med <code>select</code> och <code>filter</code></a></li>
<li class="chapter" data-level="1.7" data-path="datahantering-och-grafer.html"><a href="datahantering-och-grafer.html#grafer-med-ggplot2"><i class="fa fa-check"></i><b>1.7</b> Grafer med <code>ggplot2</code></a></li>
<li class="chapter" data-level="1.8" data-path="datahantering-och-grafer.html"><a href="datahantering-och-grafer.html#ai-uppgift-i"><i class="fa fa-check"></i><b>1.8</b> AI-uppgift I</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="beskrivande-statistik.html"><a href="beskrivande-statistik.html"><i class="fa fa-check"></i><b>2</b> Beskrivande statistik</a>
<ul>
<li class="chapter" data-level="2.1" data-path="beskrivande-statistik.html"><a href="beskrivande-statistik.html#repetition-från-datorövning-1"><i class="fa fa-check"></i><b>2.1</b> Repetition från datorövning 1</a></li>
<li class="chapter" data-level="2.2" data-path="beskrivande-statistik.html"><a href="beskrivande-statistik.html#import-av-data-från-en-excelfil"><i class="fa fa-check"></i><b>2.2</b> Import av data från en Excelfil</a></li>
<li class="chapter" data-level="2.3" data-path="beskrivande-statistik.html"><a href="beskrivande-statistik.html#ändra-och-skapa-nya-kolumner-med-mutate"><i class="fa fa-check"></i><b>2.3</b> Ändra och skapa nya kolumner med <code>mutate</code></a></li>
<li class="chapter" data-level="2.4" data-path="beskrivande-statistik.html"><a href="beskrivande-statistik.html#sammanfattande-lägesmått"><i class="fa fa-check"></i><b>2.4</b> Sammanfattande lägesmått</a></li>
<li class="chapter" data-level="2.5" data-path="beskrivande-statistik.html"><a href="beskrivande-statistik.html#sammanfattande-spridningsmått"><i class="fa fa-check"></i><b>2.5</b> Sammanfattande spridningsmått</a></li>
<li class="chapter" data-level="2.6" data-path="beskrivande-statistik.html"><a href="beskrivande-statistik.html#ordna-upp-beskrivande-statistik-och-exportera"><i class="fa fa-check"></i><b>2.6</b> Ordna upp beskrivande statistik och exportera</a></li>
<li class="chapter" data-level="2.7" data-path="beskrivande-statistik.html"><a href="beskrivande-statistik.html#kumulativt-medelvärde"><i class="fa fa-check"></i><b>2.7</b> Kumulativt medelvärde</a></li>
<li class="chapter" data-level="2.8" data-path="beskrivande-statistik.html"><a href="beskrivande-statistik.html#bonus.-tredimensionella-grafer-med-plotly"><i class="fa fa-check"></i><b>2.8</b> Bonus. Tredimensionella grafer med <code>plotly</code></a></li>
<li class="chapter" data-level="2.9" data-path="beskrivande-statistik.html"><a href="beskrivande-statistik.html#ai-uppgift-ii"><i class="fa fa-check"></i><b>2.9</b> AI-uppgift II</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="ett-stickprov-av-normalfördelad-data.html"><a href="ett-stickprov-av-normalfördelad-data.html"><i class="fa fa-check"></i><b>3</b> Ett stickprov av normalfördelad data</a>
<ul>
<li class="chapter" data-level="3.1" data-path="ett-stickprov-av-normalfördelad-data.html"><a href="ett-stickprov-av-normalfördelad-data.html#repetition-från-datorövning-2"><i class="fa fa-check"></i><b>3.1</b> Repetition från datorövning 2</a></li>
<li class="chapter" data-level="3.2" data-path="ett-stickprov-av-normalfördelad-data.html"><a href="ett-stickprov-av-normalfördelad-data.html#test-av-medelvärde-för-normalfördelad-data"><i class="fa fa-check"></i><b>3.2</b> Test av medelvärde för normalfördelad data</a></li>
<li class="chapter" data-level="3.3" data-path="ett-stickprov-av-normalfördelad-data.html"><a href="ett-stickprov-av-normalfördelad-data.html#konfidensintervall-för-normalfördelad-data"><i class="fa fa-check"></i><b>3.3</b> Konfidensintervall för normalfördelad data</a></li>
<li class="chapter" data-level="3.4" data-path="ett-stickprov-av-normalfördelad-data.html"><a href="ett-stickprov-av-normalfördelad-data.html#normalfördelad-data-och-centrala-gränsvärdesatsen"><i class="fa fa-check"></i><b>3.4</b> Normalfördelad data och centrala gränsvärdesatsen</a></li>
<li class="chapter" data-level="3.5" data-path="ett-stickprov-av-normalfördelad-data.html"><a href="ett-stickprov-av-normalfördelad-data.html#centrala-gränsvärdesatsen"><i class="fa fa-check"></i><b>3.5</b> Centrala gränsvärdesatsen</a></li>
<li class="chapter" data-level="3.6" data-path="ett-stickprov-av-normalfördelad-data.html"><a href="ett-stickprov-av-normalfördelad-data.html#bonus.-simuleringar-för-t-test-och-konfidensintervall"><i class="fa fa-check"></i><b>3.6</b> Bonus. Simuleringar för t-test och konfidensintervall</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="ett-stickprov-av-icke-normalfördelad-data.html"><a href="ett-stickprov-av-icke-normalfördelad-data.html"><i class="fa fa-check"></i><b>4</b> Ett stickprov av icke-normalfördelad data</a>
<ul>
<li class="chapter" data-level="4.1" data-path="ett-stickprov-av-icke-normalfördelad-data.html"><a href="ett-stickprov-av-icke-normalfördelad-data.html#repetition-av-datorövning-3"><i class="fa fa-check"></i><b>4.1</b> Repetition av datorövning 3</a></li>
<li class="chapter" data-level="4.2" data-path="ett-stickprov-av-icke-normalfördelad-data.html"><a href="ett-stickprov-av-icke-normalfördelad-data.html#proportioner-från-binär-data"><i class="fa fa-check"></i><b>4.2</b> Proportioner från binär data</a></li>
<li class="chapter" data-level="4.3" data-path="ett-stickprov-av-icke-normalfördelad-data.html"><a href="ett-stickprov-av-icke-normalfördelad-data.html#konfidensintervall-för-proportioner"><i class="fa fa-check"></i><b>4.3</b> Konfidensintervall för proportioner</a></li>
<li class="chapter" data-level="4.4" data-path="ett-stickprov-av-icke-normalfördelad-data.html"><a href="ett-stickprov-av-icke-normalfördelad-data.html#chi-två-test-för-goodness-of-fit"><i class="fa fa-check"></i><b>4.4</b> Chi-två-test för goodness-of-fit</a></li>
<li class="chapter" data-level="4.5" data-path="ett-stickprov-av-icke-normalfördelad-data.html"><a href="ett-stickprov-av-icke-normalfördelad-data.html#chi-två-test-när-någon-parameter-skattas-från-datan"><i class="fa fa-check"></i><b>4.5</b> Chi-två-test när någon parameter skattas från datan</a></li>
<li class="chapter" data-level="4.6" data-path="ett-stickprov-av-icke-normalfördelad-data.html"><a href="ett-stickprov-av-icke-normalfördelad-data.html#bonus.-interaktiva-kartor-med-leaflet"><i class="fa fa-check"></i><b>4.6</b> Bonus. Interaktiva kartor med leaflet</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="test-för-två-stickprov.html"><a href="test-för-två-stickprov.html"><i class="fa fa-check"></i><b>5</b> Test för två stickprov</a>
<ul>
<li class="chapter" data-level="5.1" data-path="test-för-två-stickprov.html"><a href="test-för-två-stickprov.html#repetition-av-datorövning-4"><i class="fa fa-check"></i><b>5.1</b> Repetition av datorövning 4</a></li>
<li class="chapter" data-level="5.2" data-path="test-för-två-stickprov.html"><a href="test-för-två-stickprov.html#två-stickprov-och-normalfördelad-data"><i class="fa fa-check"></i><b>5.2</b> Två stickprov och normalfördelad data</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="test-för-två-stickprov.html"><a href="test-för-två-stickprov.html#t-test-för-två-matchade-stickprov"><i class="fa fa-check"></i><b>5.2.1</b> t-test för två matchade stickprov</a></li>
<li class="chapter" data-level="5.2.2" data-path="test-för-två-stickprov.html"><a href="test-för-två-stickprov.html#t-test-för-två-oberoende-stickprov"><i class="fa fa-check"></i><b>5.2.2</b> t-test för två oberoende stickprov</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="test-för-två-stickprov.html"><a href="test-för-två-stickprov.html#z-test-och-konfidensintervall-för-två-proportioner"><i class="fa fa-check"></i><b>5.3</b> z-test och konfidensintervall för två proportioner</a></li>
<li class="chapter" data-level="5.4" data-path="test-för-två-stickprov.html"><a href="test-för-två-stickprov.html#chi-två-test-för-korstabeller"><i class="fa fa-check"></i><b>5.4</b> Chi-två-test för korstabeller</a></li>
<li class="chapter" data-level="5.5" data-path="test-för-två-stickprov.html"><a href="test-för-två-stickprov.html#bonus.-bilder-i-r"><i class="fa fa-check"></i><b>5.5</b> Bonus. Bilder i R</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="variansanalys.html"><a href="variansanalys.html"><i class="fa fa-check"></i><b>6</b> Variansanalys</a>
<ul>
<li class="chapter" data-level="6.1" data-path="variansanalys.html"><a href="variansanalys.html#repetition-av-datorövning-5"><i class="fa fa-check"></i><b>6.1</b> Repetition av datorövning 5</a></li>
<li class="chapter" data-level="6.2" data-path="variansanalys.html"><a href="variansanalys.html#allmänt"><i class="fa fa-check"></i><b>6.2</b> Allmänt</a></li>
<li class="chapter" data-level="6.3" data-path="variansanalys.html"><a href="variansanalys.html#variansanalys.-en-faktor"><i class="fa fa-check"></i><b>6.3</b> Variansanalys. En faktor</a></li>
<li class="chapter" data-level="6.4" data-path="variansanalys.html"><a href="variansanalys.html#variansanalys.-en-faktor-med-block"><i class="fa fa-check"></i><b>6.4</b> Variansanalys. En faktor med block</a></li>
<li class="chapter" data-level="6.5" data-path="variansanalys.html"><a href="variansanalys.html#variansanalys.-två-faktorer-med-block"><i class="fa fa-check"></i><b>6.5</b> Variansanalys. Två faktorer med block</a></li>
<li class="chapter" data-level="6.6" data-path="variansanalys.html"><a href="variansanalys.html#modellantaganden-och-residualer"><i class="fa fa-check"></i><b>6.6</b> Modellantaganden och residualer</a></li>
<li class="chapter" data-level="6.7" data-path="variansanalys.html"><a href="variansanalys.html#bonus.-statistik-för-ekologi"><i class="fa fa-check"></i><b>6.7</b> Bonus. Statistik för ekologi</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="regression-och-korrelation.html"><a href="regression-och-korrelation.html"><i class="fa fa-check"></i><b>7</b> Regression och korrelation</a>
<ul>
<li class="chapter" data-level="7.1" data-path="regression-och-korrelation.html"><a href="regression-och-korrelation.html#repetition-av-datorövning-6"><i class="fa fa-check"></i><b>7.1</b> Repetition av datorövning 6</a></li>
<li class="chapter" data-level="7.2" data-path="regression-och-korrelation.html"><a href="regression-och-korrelation.html#regression"><i class="fa fa-check"></i><b>7.2</b> Regression</a></li>
<li class="chapter" data-level="7.3" data-path="regression-och-korrelation.html"><a href="regression-och-korrelation.html#korrelation"><i class="fa fa-check"></i><b>7.3</b> Korrelation</a></li>
<li class="chapter" data-level="7.4" data-path="regression-och-korrelation.html"><a href="regression-och-korrelation.html#bonus.-skrapa-data-från-webbsidor"><i class="fa fa-check"></i><b>7.4</b> Bonus. Skrapa data från webbsidor</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">R-anvisningar till <em>Grundläggande statistik</em></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="ett-stickprov-av-icke-normalfördelad-data" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">4</span> Ett stickprov av icke-normalfördelad data<a href="ett-stickprov-av-icke-normalfördelad-data.html#ett-stickprov-av-icke-normalfördelad-data" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Datorövning 4 handlar om hypotestest och konfidensintervall för ett stickprov av icke-normalfördelad data. Efter övningen ska vi kunna</p>
<ul>
<li><p>genomföra och tolka ett z-test för proportioner,</p></li>
<li><p>genomföra och tolka ett chi-två-test för nominal data</p></li>
<li><p>beräkna och tolka ett konfidensintervall för proportioner,</p></li>
<li><p>använda simulerad data för att förstå testens egenskaper.</p></li>
</ul>
<p>Om det finns tid för en bonussektion kommer vi också titta på interaktiva kartor med <code>leaflet</code>.</p>
<div id="repetition-av-datorövning-3" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> Repetition av datorövning 3<a href="ett-stickprov-av-icke-normalfördelad-data.html#repetition-av-datorövning-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>När man startar en ny R-session bör man ladda de paket man vet kommer behövas med <code>library()</code>. Om paket inte finns installerade måste man först köra <code>install.packages()</code>.</p>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb164-1"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb164-1" tabindex="-1"></a><span class="co"># install.packages(&quot;tidyverse&quot;)</span></span>
<span id="cb164-2"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb164-2" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
<p>I datorövning 4 tittade vi på analys av ett stickprov av normalfördelad data. Det underliggande upplägget är att vi vill säga något om en population genom att titta på ett stickprov. Ett <em>t-test</em> kan användas för att testa en given <em>nollhypotes</em>. Ett konfidensintervall ringar in populationens medelvärde med en viss konfidensgrad - oftast 95 procent. Ett normalfördelningsantagande kan undersökas med histogram eller QQ-grafer.</p>
<p>Ta som exempel följande data på jord-pH och låt oss anta att det är relevant att testa om populationens medelvärde är 7.</p>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb165-1" tabindex="-1"></a>dat_pH <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">pH =</span> <span class="fu">c</span>(<span class="fl">6.3</span>, <span class="fl">6.55</span>, <span class="fl">6.75</span>, <span class="fl">6.4</span>, <span class="fl">7.25</span>, <span class="fl">6.65</span>, <span class="fl">6.8</span>, <span class="fl">7.3</span>, <span class="fl">7.15</span>, <span class="fl">6.7</span>))</span>
<span id="cb165-2"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb165-2" tabindex="-1"></a></span>
<span id="cb165-3"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb165-3" tabindex="-1"></a><span class="fu">ggplot</span>(dat_pH, <span class="fu">aes</span>(pH, <span class="dv">0</span>)) <span class="sc">+</span></span>
<span id="cb165-4"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb165-4" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb165-5"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb165-5" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">7</span>, <span class="at">size =</span> <span class="dv">5</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb165-6"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb165-6" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.y =</span> <span class="fu">element_blank</span>(), </span>
<span id="cb165-7"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb165-7" tabindex="-1"></a>        <span class="at">axis.title.y =</span> <span class="fu">element_blank</span>(), </span>
<span id="cb165-8"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb165-8" tabindex="-1"></a>        <span class="at">axis.ticks =</span> <span class="fu">element_blank</span>())</span></code></pre></div>
<p><img src="R-anvisningar_files/figure-html/unnamed-chunk-126-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Hypoteser ges av</p>
<ul>
<li>H0: mu lika med 7</li>
<li>H1: mu ej lika med 7</li>
</ul>
<p>Testet kan genomföras med funktionen <code>t.test()</code>.</p>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb166-1"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb166-1" tabindex="-1"></a><span class="fu">t.test</span>(dat_pH<span class="sc">$</span>pH, <span class="at">mu =</span> <span class="dv">7</span>)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  dat_pH$pH
## t = -1.9624, df = 9, p-value = 0.08132
## alternative hypothesis: true mean is not equal to 7
## 95 percent confidence interval:
##  6.537164 7.032836
## sample estimates:
## mean of x 
##     6.785</code></pre>
<p>Ett p-värde över 0.05 ger att vi inte förkastar nollhypotesen - den observerade skillnaden mot 7 är inte statistiskt signifikant. Konfidensintervallet ger att populationens medelvärde ligger mellan 6.54 och 7.03 med 95 procents konfidens.</p>
<p>En QQ-graf kan visa om det finns några avvikelser från normalantagandet. Med små datamängder är det oftast svårt att se några tydliga tecken på icke-normalitet.</p>
<div class="sourceCode" id="cb168"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb168-1"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb168-1" tabindex="-1"></a><span class="fu">ggplot</span>(dat_pH, <span class="fu">aes</span>(<span class="at">sample =</span> pH)) <span class="sc">+</span></span>
<span id="cb168-2"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb168-2" tabindex="-1"></a>  <span class="fu">geom_qq</span>() <span class="sc">+</span></span>
<span id="cb168-3"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb168-3" tabindex="-1"></a>  <span class="fu">geom_qq_line</span>()</span></code></pre></div>
<p><img src="R-anvisningar_files/figure-html/unnamed-chunk-128-1.png" width="288" style="display: block; margin: auto;" /></p>
</div>
<div id="proportioner-från-binär-data" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> Proportioner från binär data<a href="ett-stickprov-av-icke-normalfördelad-data.html#proportioner-från-binär-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Binär data är data där en observation har ett av två utfall, vilka kan kodas som noll och ett. Man talar ibland om utfallet ett som ett <em>positivt</em> utfall. Binär data kan sammanfattas med en proportion - antalet positiva utfall delat på det totala antalet upprepningar. En proportion kan testas med ett z-test för proportioner (eller <em>relativ frekvens</em>). Testet följer stegen för hypotestest (Hypoteser - Testvärde - Testfördelning - P-värde (eller jämförelse med kritiskt värde) - Slutsats).</p>
<p>Låt oss importera lite exempeldata och beräkna ett exempel. Följande rad importerar matchresultat i fotbollsallsvenskan för damer 2000-2020.</p>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb169-1"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb169-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb169-2"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb169-2" tabindex="-1"></a>dat_alls <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;https://raw.githubusercontent.com/adamflr/ST0060/main/Data/Allsvenskan%2C%20damer%2C%202000-2020.csv&quot;</span>)</span>
<span id="cb169-3"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb169-3" tabindex="-1"></a></span>
<span id="cb169-4"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb169-4" tabindex="-1"></a><span class="fu">ggplot</span>(dat_alls, <span class="fu">aes</span>(hemmamal, bortamal)) <span class="sc">+</span></span>
<span id="cb169-5"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb169-5" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">size =</span> <span class="fl">0.1</span>)</span></code></pre></div>
<p><img src="R-anvisningar_files/figure-html/unnamed-chunk-129-1.png" width="672" style="display: block; margin: auto;" /></p>
<div class="exercise">
<p><span id="exr:unlabeled-div-68" class="exercise"><strong>Uppgift 4.1  (En interaktiv målgraf) </strong></span>Kör stycket nedan för en interaktiv målgraf. Vilken match gav det högsta antalet gjorda bortamål?</p>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb170-1"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb170-1" tabindex="-1"></a><span class="co"># install.packages(plotly)</span></span>
<span id="cb170-2"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb170-2" tabindex="-1"></a><span class="fu">library</span>(plotly)</span>
<span id="cb170-3"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb170-3" tabindex="-1"></a>g <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(dat_alls, <span class="fu">aes</span>(hemmamal, bortamal, <span class="at">text =</span> <span class="fu">paste</span>(sasong, hemma, <span class="st">&quot;-&quot;</span>, borta))) <span class="sc">+</span></span>
<span id="cb170-4"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb170-4" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">size =</span> <span class="fl">0.1</span>)</span>
<span id="cb170-5"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb170-5" tabindex="-1"></a></span>
<span id="cb170-6"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb170-6" tabindex="-1"></a><span class="fu">ggplotly</span>(g)</span></code></pre></div>
</div>
<p>Gammal bollkunskap säger att var tredje match är en bortavinst. Vi kan testa det med ett z-test för proportioner. För att ta fram antalet bortasegrar och totalt antal matcher använder vi <code>count()</code> på kolumnen <code>resultat</code>. Man kan också använda funktionen <code>table()</code> för ett liknande resultat.</p>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb171-1"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb171-1" tabindex="-1"></a>dat_alls <span class="sc">%&gt;%</span> <span class="fu">count</span>(resultat)</span></code></pre></div>
<pre><code>## # A tibble: 3 × 2
##   resultat       n
##   &lt;chr&gt;      &lt;int&gt;
## 1 Bortaseger   947
## 2 Hemmaseger  1285
## 3 Oavgjort     518</code></pre>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb173-1"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb173-1" tabindex="-1"></a><span class="fu">table</span>(dat_alls<span class="sc">$</span>resultat)</span></code></pre></div>
<pre><code>## 
## Bortaseger Hemmaseger   Oavgjort 
##        947       1285        518</code></pre>
<p>Datan har 947 bortasegrar av totalt 947 + 1803 matcher. Vår skattade proportion <code>p</code> och totala antal <code>n</code> är alltså</p>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb175-1"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb175-1" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">947</span> <span class="sc">+</span> <span class="dv">1803</span></span>
<span id="cb175-2"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb175-2" tabindex="-1"></a>p_est <span class="ot">&lt;-</span> <span class="dv">947</span> <span class="sc">/</span> n</span>
<span id="cb175-3"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb175-3" tabindex="-1"></a></span>
<span id="cb175-4"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb175-4" tabindex="-1"></a>p_est</span></code></pre></div>
<pre><code>## [1] 0.3443636</code></pre>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb177-1"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb177-1" tabindex="-1"></a>n</span></code></pre></div>
<pre><code>## [1] 2750</code></pre>
<p>För att genomföra ett z-test sätter vi upp hypoteser om proportionen bortasegrar.</p>
<ul>
<li>Nollhypotes H0: p lika med 0.33</li>
<li>Alternativhypotes H1: p ej lika med 0.33</li>
</ul>
<p>Ett test kan köras i R med <code>prop.test()</code>.</p>
<div class="sourceCode" id="cb179"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb179-1"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb179-1" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="at">x =</span> <span class="dv">947</span>, <span class="at">n =</span> <span class="dv">2750</span>, <span class="at">p =</span> <span class="fl">0.33</span>, <span class="at">correct =</span> F)</span></code></pre></div>
<pre><code>## 
##  1-sample proportions test without continuity correction
## 
## data:  947 out of 2750, null probability 0.33
## X-squared = 2.5661, df = 1, p-value = 0.1092
## alternative hypothesis: true p is not equal to 0.33
## 95 percent confidence interval:
##  0.3268327 0.3623288
## sample estimates:
##         p 
## 0.3443636</code></pre>
<p>P-värdet ställs mot en förbestämd signifikansnivå (vanligen 5 procent). I det här fallet leder det höga p-värdet till att nollhypotesen accepteras.</p>
<p>Om vi tar en närmre titt på testets steg brörjar vi med att beräkna ett testvärde.</p>
<div class="sourceCode" id="cb181"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb181-1"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb181-1" tabindex="-1"></a>p0 <span class="ot">&lt;-</span> <span class="fl">0.33</span></span>
<span id="cb181-2"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb181-2" tabindex="-1"></a>z_value <span class="ot">&lt;-</span> (p_est <span class="sc">-</span> p0) <span class="sc">/</span> <span class="fu">sqrt</span>(p0 <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p0) <span class="sc">/</span> n)</span>
<span id="cb181-3"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb181-3" tabindex="-1"></a>z_value</span></code></pre></div>
<pre><code>## [1] 1.601904</code></pre>
<p>Därefter kan p-värdet räknas ut som arean under en standardiserad normalfördelning bortom z-värdet. Eftersom vi har en tvåsidig mothypotes adderas de två svansarna.</p>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb183-1"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb183-1" tabindex="-1"></a>dat_norm <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">4</span>, <span class="dv">4</span>, <span class="fl">0.1</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb183-2"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb183-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">p =</span> <span class="fu">dnorm</span>(x))</span>
<span id="cb183-3"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb183-3" tabindex="-1"></a></span>
<span id="cb183-4"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb183-4" tabindex="-1"></a><span class="fu">ggplot</span>(dat_norm) <span class="sc">+</span></span>
<span id="cb183-5"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb183-5" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(x, p)) <span class="sc">+</span></span>
<span id="cb183-6"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb183-6" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">ymin =</span> <span class="dv">0</span>, <span class="at">ymax =</span> p), <span class="at">data =</span> dat_norm <span class="sc">%&gt;%</span> <span class="fu">filter</span>(x <span class="sc">&gt;</span> <span class="fu">abs</span>(z_value)), <span class="at">fill =</span> <span class="st">&quot;salmon&quot;</span>) <span class="sc">+</span></span>
<span id="cb183-7"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb183-7" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">ymin =</span> <span class="dv">0</span>, <span class="at">ymax =</span> p), <span class="at">data =</span> dat_norm <span class="sc">%&gt;%</span> <span class="fu">filter</span>(x <span class="sc">&lt;</span> <span class="sc">-</span><span class="fu">abs</span>(z_value)), <span class="at">fill =</span> <span class="st">&quot;salmon&quot;</span>)</span></code></pre></div>
<p><img src="R-anvisningar_files/figure-html/unnamed-chunk-135-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Areans yta kan tas fram med normalfördelningens fördelningsfunktion <code>pnorm()</code>.</p>
<div class="sourceCode" id="cb184"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb184-1"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb184-1" tabindex="-1"></a><span class="dv">2</span> <span class="sc">*</span> <span class="fu">pnorm</span>(<span class="sc">-</span>z_value)</span></code></pre></div>
<pre><code>## [1] 0.1091769</code></pre>
<p>Testets p-värde är ungefär 11 procent. Vår observation är alltså inte ett orimligt utfall om den faktiska sannolikheten för bortaseger är 0.33 och vi kan inte förkasta nollhypotesen på femprocentsnivån.</p>
<p>Om man löste uppgiften för hand skulle man istället för att beräkna p-värdet jämföra z-värdet med ett kritisk värde ur en tabell. Det kritiska värdet för fem-procentig signifikans är 1.96. Vi kan också ta fram det genom <code>qnorm(0.975)</code>.</p>
<p>Vi kan jämföra den beräkning med den direkta R-funktionen.</p>
<div class="sourceCode" id="cb186"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb186-1"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb186-1" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="at">x =</span> <span class="dv">947</span>, <span class="at">n =</span> <span class="dv">2750</span>, <span class="at">p =</span> <span class="fl">0.33</span>, <span class="at">correct =</span> F)</span></code></pre></div>
<pre><code>## 
##  1-sample proportions test without continuity correction
## 
## data:  947 out of 2750, null probability 0.33
## X-squared = 2.5661, df = 1, p-value = 0.1092
## alternative hypothesis: true p is not equal to 0.33
## 95 percent confidence interval:
##  0.3268327 0.3623288
## sample estimates:
##         p 
## 0.3443636</code></pre>
<p>Den stegvisa beräkningen gav samma utfall som funktionen (<code>p-value = 0.01092</code>). Funktionen ger inte z-värdet utan ett chi-två-värde (2.5661). Här är det värdet lika med z-värdet i kvadrat.</p>
<div class="sourceCode" id="cb188"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb188-1"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb188-1" tabindex="-1"></a>z_value<span class="sc">^</span><span class="dv">2</span></span></code></pre></div>
<pre><code>## [1] 2.566095</code></pre>
<div class="exercise">
<p><span id="exr:unlabeled-div-69" class="exercise"><strong>Uppgift 4.2  (Ensidigt test) </strong></span>Titta på hjälpsidan med <code>?prop.test</code>. Hur genomför man ett ensidigt test? Gör lämpligt tillägg för att testa om andelen bortasegrar är större än 0.33.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-70" class="exercise"><strong>Uppgift 4.3  (Test för proportionen oavgjorda) </strong></span>Samma gamla bollkunskap säger att 20 procent av matcher blir oavgjorda. I datan är 518 av 2750 matcher oavgjorda. Ställ upp hypoteser och fyll i koden nedan för att testa om bollkunskapen stämmer.</p>
<div class="sourceCode" id="cb190"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb190-1"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb190-1" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="at">x =</span> ___, <span class="at">n =</span> ___, <span class="at">p =</span> ___, <span class="at">correct =</span> F)</span></code></pre></div>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-71" class="exercise"><strong>Uppgift 4.4  (Test för proportionen hemmasegrar) </strong></span>Slutligen är då resten av matcherna, 1285 av 2750, hemmasegrar. Gammal bollkunskap säger: <em>47 procent av alla matcher är hemmasegrar</em>. Genomför ett z-test för att testa det påstående.</p>
<div class="sourceCode" id="cb191"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb191-1"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb191-1" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="at">x =</span> ___, <span class="at">n =</span> ___, <span class="at">p =</span> ___, <span class="at">correct =</span> F)</span></code></pre></div>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-72" class="exercise"><strong>Uppgift 4.5  (Population och stickprov) </strong></span>Ett hypotestest bygger på en underliggande tanke med en population (med någon för oss okänd proportion positiva utfall) och ett stickprov (i vilket vi kan observera andelen positiva utfall). Det är inte alltid uppenbart vad som egentligen är populationen. I fallet med fotbollsdatan, vad kan ses som populationen? Hur långt skulle man kunna generalisera de slutsatser man kan dra från datan?</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-73" class="exercise"><strong>Uppgift 4.6  (Guldfiskgenetik) </strong></span>(Fråga från Olsson, <em>Biometri</em>) En teori inom genetik förutsäger att tre fjärdedelar i en grupp guldfiskar ska ha genomskinliga fjäll. Observationer ger att nittio av hundra har genomskinliga fjäll. Genomför ett test med <code>prop.test()</code> för att se om den faktiska proportionen skiljer sig från 0.75. Lös gärna först uppgiften för hand eller med miniräknare.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-74" class="exercise"><strong>Uppgift 4.7  (Mer guldfiskgenetik) </strong></span>(Fråga från Olsson, <em>Biometri</em>) En konkurrerande teori inom genetik förutsäger att femton sextondelar (proportionen 0.9375) ska ha genomskinliga fjäll. Observationer ger att nittio av hundra har genomskinliga fjäll. Genomför ett test med <code>prop.test()</code> för att se om proportionen skiljer sig från 0.9375. Lös gärna först uppgiften för hand eller med miniräknare.</p>
</div>
<p>Hypotestestet för proportioner som används här, <em>z-testet</em>, bygger på en normalapproximation av en binomialfördelning. Approximation blir bättre när antalet observationer är stort och nollhypotesens värde p0 ligger nära 0.5. En vanlig tumregel för när approximationen är giltig är att n gånger p0 gånger (1 - p0) ska vara större än 10. För fotbollsdatan över oavgjorda matcher ger det 2750 * 0.2 * 0.8 vilket är klart större än 10.</p>
<div class="exercise">
<p><span id="exr:unlabeled-div-75" class="exercise"><strong>Uppgift 4.8  (Giltig approximation) </strong></span>I det andra guldfiskexemplet är antalet observationer 100 och nollhypotesens värde 0.9375. Är normalapproximationen <em>giltig</em> i det fallet?</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-76" class="exercise"><strong>Uppgift 4.9  (Fågelproportioner) </strong></span>I ett naturreservat tror man fördelningen av tre fåglar (tärnmås, fiskmås och fisktärna) är 50, 30 respektive 20 procent. En studie ger antalen 115, 54 respektive 31. Genomför tre z-test för att testa den antagna andelarna. För tärnmås får man till exempel <code>prop.test(115, 200, p = 0.5, correct = F)</code>.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-77" class="exercise"><strong>Uppgift 4.10  (Förbestämd signifikans) </strong></span>En intressant egenskap hos proportionstest är att man redan i förväg kan beräkna vilka utfall som ger signifikanta resulat. Säg att man har möjlighet att göra 100 replikat. Ändra i stycket nedan för att hitta det högsta värde på x som ger ett <em>icke</em>-signifikant utfall.</p>
<div class="sourceCode" id="cb192"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb192-1"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb192-1" tabindex="-1"></a><span class="fu">prop.test</span>(x, <span class="at">n =</span> <span class="dv">100</span>, <span class="at">p =</span> <span class="fl">0.5</span>, <span class="at">correct =</span> F)</span></code></pre></div>
<p>Det är möjligt att göra liknande beräkningar för ett t-test för normalfördelad data, men då måste man göra antaganden om standardavvikelsens storlek.</p>
</div>
</div>
<div id="konfidensintervall-för-proportioner" class="section level2 hasAnchor" number="4.3">
<h2><span class="header-section-number">4.3</span> Konfidensintervall för proportioner<a href="ett-stickprov-av-icke-normalfördelad-data.html#konfidensintervall-för-proportioner" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Konstruktionen av ett konfidensintervall för en proportion är ganska lik konstruktionen för ett medelvärde. För en skattad proportion p och antal observationer n kan man beräkna p plus/minus ett z-värde från tabell gånger medelfelet, där medelfelet ges av roten ur p * (1 - p) / n. För exemplet med bortasegrar i allsvenskan är p = 0.344 och n = 2750. Tabellvärdet hämtas från en tabell över kvantiler. För ett 95-procentigt konfidensintervall tar vi kvantilen 0.975 (2.5 procent i respektive svans) vilket ger värdet 1.96. Konfidensintervallet ges av</p>
<div class="sourceCode" id="cb193"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb193-1"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb193-1" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">947</span> <span class="sc">+</span> <span class="dv">1803</span></span>
<span id="cb193-2"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb193-2" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="dv">947</span> <span class="sc">/</span> n</span>
<span id="cb193-3"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb193-3" tabindex="-1"></a></span>
<span id="cb193-4"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb193-4" tabindex="-1"></a>p <span class="sc">-</span> <span class="fl">1.96</span> <span class="sc">*</span> <span class="fu">sqrt</span>(p <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p) <span class="sc">/</span> n)</span></code></pre></div>
<pre><code>## [1] 0.3266042</code></pre>
<div class="sourceCode" id="cb195"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb195-1"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb195-1" tabindex="-1"></a>p <span class="sc">+</span> <span class="fl">1.96</span> <span class="sc">*</span> <span class="fu">sqrt</span>(p <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p) <span class="sc">/</span> n)</span></code></pre></div>
<pre><code>## [1] 0.3621231</code></pre>
<p>Notera att 0.33, det värde som var nollhypotesen i det tidigare testet, <em>ingår</em> i intervallet. Om man tittar på utskriften från <code>prop.test()</code> kan man se ett konfidensintervall. Det intervallet är dock inte beräknat på samma sätt den formel som förekommer på föreläsningarna. För att få matchande utskrift kan vi använda paketet <code>binom</code> och funktionen <code>binom.asymp()</code>.</p>
<div class="sourceCode" id="cb197"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb197-1"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb197-1" tabindex="-1"></a><span class="co">#install.packages(&quot;binom&quot;)</span></span>
<span id="cb197-2"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb197-2" tabindex="-1"></a><span class="fu">library</span>(binom)</span>
<span id="cb197-3"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb197-3" tabindex="-1"></a><span class="fu">binom.asymp</span>(<span class="at">x =</span> <span class="dv">947</span>, <span class="at">n =</span> <span class="dv">2750</span>)</span></code></pre></div>
<pre><code>##       method   x    n      mean     lower     upper
## 1 asymptotic 947 2750 0.3443636 0.3266045 0.3621228</code></pre>
<div class="exercise">
<p><span id="exr:unlabeled-div-78" class="exercise"><strong>Uppgift 4.11  (99-procentigt konfidensintervall) </strong></span>Gör lämplig ändring i koden nedan för att beräkna ett 99-procentigt konfidensintervall för andelen bortasegrar.</p>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb199-1"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb199-1" tabindex="-1"></a><span class="fu">binom.asymp</span>(<span class="at">x =</span> <span class="dv">947</span>, <span class="at">n =</span> <span class="dv">2750</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code></pre></div>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-79" class="exercise"><strong>Uppgift 4.12  (Perfekta utfall) </strong></span>Vad händer om man försöker räkna ut ett konfidensintervall för ett perfekt utfall - t.ex. om man får 100 av 100 positiva utfall?</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-80" class="exercise"><strong>Uppgift 4.13  (Konfidensintervall för guldfiskar) </strong></span>Använd funktionen <code>binom.asymp()</code> för att ta fram konfidensintervallet för andelen guldfiskar från den tidigare uppgiften. Hur förhåller sig resultatet till nollhypotesernas värden (0.75 respektive 0.9375)? Gör motsvarande beräkning med miniräknare.</p>
</div>
</div>
<div id="chi-två-test-för-goodness-of-fit" class="section level2 hasAnchor" number="4.4">
<h2><span class="header-section-number">4.4</span> Chi-två-test för goodness-of-fit<a href="ett-stickprov-av-icke-normalfördelad-data.html#chi-två-test-för-goodness-of-fit" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Ett proportionstest kan ses som ett test av en variabel med två möjliga klasser som utfall. Ett <em>goodness-of-fit</em>-test utvecklar det till valfritt antal klasser. Testet utförs som ett chi-två-test genom att beräkna ett observerat antal O och ett förväntat antal E för varje klass. Testvärdet ges av att man beräknar (O - E)^2 / E för varje klass och sedan summerar. Testfunktionen är en chi-två-fördelning där antalet frihetsgrader beror på antalet klasser.</p>
<p>Låt oss göra ett exempel baserat på fotbollsdatan. Där hade vi utfallet 947, 518 och 1285 för bortaseger, oavgjort och hemmaseger. Klassisk bollkunskap gav oss sannolikheterna 33, 20 och 47 procent. Testets hypoteser ges av</p>
<p>H0: sannolikheterna för de olika utfallet ges av 33, 20 respektive 47 procent</p>
<p>H1: minst något utfall har en annan sannolikhet än 33, 20 respektive 47 procent</p>
<p>För att få de förväntade värdena E multipliceras nollhypotesens sannolikheter med det totala antalet matcher.</p>
<div class="sourceCode" id="cb200"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb200-1"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb200-1" tabindex="-1"></a>O <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">947</span>, <span class="dv">518</span>, <span class="dv">1285</span>)</span>
<span id="cb200-2"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb200-2" tabindex="-1"></a>E <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.33</span>,<span class="fl">0.20</span>,<span class="fl">0.47</span>) <span class="sc">*</span> <span class="dv">2750</span></span></code></pre></div>
<div class="exercise">
<p><span id="exr:unlabeled-div-81" class="exercise"><strong>Uppgift 4.14  (Granska E) </strong></span>Skriv ut objektet <code>E</code> och jämför med de observerade värdena. Notera att de förväntade värdena inte måste vara heltal, trots att de observerade värdena förstås alltid kommer vara det.</p>
</div>
<p>Testvärdet beräknas genom formeln för varje term följt av summan.</p>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb201-1"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb201-1" tabindex="-1"></a>chisq_value <span class="ot">&lt;-</span> <span class="fu">sum</span>((O <span class="sc">-</span> E)<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> E)</span></code></pre></div>
<p>P-värdet beräknas från en chi-två-fördelning. Antalet frihetsgrader ges av antalet klasser minus antalet skattade parametrar minus ett. I det här fallet har inga parametrar skattats från datan så antalet frihetsgrader blir två. Ett chi-två-test beräknas med kvadrater så vi är enbart intresserade av högra svansen.</p>
<div class="sourceCode" id="cb202"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb202-1"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb202-1" tabindex="-1"></a>dat_chisq <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">10</span>, <span class="fl">0.1</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb202-2"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb202-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">p =</span> <span class="fu">dchisq</span>(x, <span class="at">df =</span> <span class="dv">2</span>))</span>
<span id="cb202-3"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb202-3" tabindex="-1"></a></span>
<span id="cb202-4"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb202-4" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb202-5"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb202-5" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(x, p), <span class="at">data =</span> dat_chisq) <span class="sc">+</span></span>
<span id="cb202-6"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb202-6" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(x, <span class="at">ymin =</span> <span class="dv">0</span>, <span class="at">ymax =</span> p), <span class="at">data =</span> dat_chisq <span class="sc">%&gt;%</span> <span class="fu">filter</span>(x <span class="sc">&gt;</span> chisq_value), <span class="at">fill =</span> <span class="st">&quot;salmon&quot;</span>)</span></code></pre></div>
<p><img src="R-anvisningar_files/figure-html/unnamed-chunk-147-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Man kan också beräkna ytan i svansen med <code>pchisq()</code>. Ett minus det resultatet ger den övre delen.</p>
<div class="sourceCode" id="cb203"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb203-1"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb203-1" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pchisq</span>(chisq_value, <span class="at">df =</span> <span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 0.1632763</code></pre>
<p>P-värdet är alltså 0.16, över den klassiska signifikansnivån på 5 procent, vilket ger att vi inte kan förkasta nollhypotesen. Om man gör ett chi-två-test för hand jämför man det observerade chi-två-värdet med ett tabellvärde över kvantiler. Tabellvärdet kan också hämtas med funktionen <code>qchisq()</code>, i det här fallet</p>
<div class="sourceCode" id="cb205"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb205-1"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb205-1" tabindex="-1"></a><span class="fu">qchisq</span>(<span class="fl">0.95</span>, <span class="at">df =</span> <span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 5.991465</code></pre>
<p>Notera att man tar 0.95 eftersom man alltid tittar på den yttre svansen i ett chi-två-test.</p>
<p>R har en inbyggd funktion för chi-två-test. Dess argument ges av observerade antal och sannolikheter.</p>
<div class="sourceCode" id="cb207"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb207-1"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb207-1" tabindex="-1"></a><span class="fu">chisq.test</span>(O, <span class="at">p =</span> <span class="fu">c</span>(<span class="fl">0.33</span>, <span class="fl">0.2</span>, <span class="fl">0.47</span>))</span></code></pre></div>
<pre><code>## 
##  Chi-squared test for given probabilities
## 
## data:  O
## X-squared = 3.6246, df = 2, p-value = 0.1633</code></pre>
<p>Testet ger samma chi-två-värde och p-värde som beräknats ovan.</p>
<div class="exercise">
<p><span id="exr:unlabeled-div-82" class="exercise"><strong>Uppgift 4.15  (Chi-två med två klasser) </strong></span>Situationen med flera klasser kan som sagt ses som en generalisering av fallet med två klasser. Det är alltså logiskt att chi-två-test kan användas även när man har två klasser. Följande exempel ger samma test som vi sett tidigare av andelen bortasegrar.</p>
<div class="sourceCode" id="cb209"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb209-1"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb209-1" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">947</span>, <span class="dv">1803</span>), <span class="at">p =</span> <span class="fu">c</span>(<span class="fl">0.33</span>, <span class="fl">0.67</span>), <span class="at">correct =</span> F)</span></code></pre></div>
<pre><code>## 
##  Chi-squared test for given probabilities
## 
## data:  c(947, 1803)
## X-squared = 2.5661, df = 1, p-value = 0.1092</code></pre>
<p>Likt <code>prop.test()</code> sätter vi <code>correct</code> till <code>FALSE</code> för att inte göra en korrektion. Notera att <code>x</code> här anges som positiva och negativa utfall istället för positiva utfall och totalt antal utfall, vilket var fallet i <code>prop.test()</code>.</p>
<p>Använd stycket ovan som mall för att göra uppgiften om guldfiskar som ett chi-två-test. Testa nollhypotesen att andelen positiva utfall är 0.75.</p>
</div>
<p>Chi-två-testet bygger på en underliggande normal-liknande approximation. En vanlig tumregel är att alla förväntade värden ska vara större än 5. R ger en varning om så inte är fallet.</p>
<div class="sourceCode" id="cb211"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb211-1"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb211-1" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="fu">c</span>(<span class="dv">6</span>,<span class="dv">4</span>), <span class="at">p =</span> <span class="fu">c</span>(<span class="fl">0.51</span>, <span class="fl">0.49</span>))</span></code></pre></div>
<pre><code>## 
##  Chi-squared test for given probabilities
## 
## data:  c(6, 4)
## X-squared = 0.32413, df = 1, p-value = 0.5691</code></pre>
<div class="exercise">
<p><span id="exr:unlabeled-div-83" class="exercise"><strong>Uppgift 4.16  (Chi-två med lika sannolikheter) </strong></span>En vanlig tillämpning av goodness-of-fit-testet är för att testa om alla klasser är lika sannolika. En jämn fördelning är grundinställning i <code>chisq.test()</code> så i det fallet behöver man bara ange de observerade värdena. En datainsamling om M&amp;M-godis gav följande antal.</p>
<div class="sourceCode" id="cb213"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb213-1"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb213-1" tabindex="-1"></a>dat_mnm <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Color =</span> <span class="fu">c</span>(<span class="st">&quot;blue&quot;</span>, <span class="st">&quot;brown&quot;</span>, <span class="st">&quot;green&quot;</span>, <span class="st">&quot;orange&quot;</span>, <span class="st">&quot;red&quot;</span>, <span class="st">&quot;yellow&quot;</span>),</span>
<span id="cb213-2"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb213-2" tabindex="-1"></a>                      <span class="at">Count =</span> <span class="fu">c</span>(<span class="dv">180</span>, <span class="dv">80</span>, <span class="dv">88</span>, <span class="dv">160</span>, <span class="dv">134</span>, <span class="dv">166</span>))</span>
<span id="cb213-3"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb213-3" tabindex="-1"></a></span>
<span id="cb213-4"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb213-4" tabindex="-1"></a><span class="fu">ggplot</span>(dat_mnm, <span class="fu">aes</span>(Color, Count, <span class="at">fill =</span> Color)) <span class="sc">+</span></span>
<span id="cb213-5"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb213-5" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb213-6"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb213-6" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> dat_mnm<span class="sc">$</span>Color)</span></code></pre></div>
<p><img src="R-anvisningar_files/figure-html/unnamed-chunk-153-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Använd de observerade värdena i kolumnen <code>Count</code> för att testa om alla godisfärger är lika vanliga.</p>
</div>
<p>Om man har flera klasser kan det vara värdefullt att se vilken klass som bidrar mest till chi-två-värdet. Det kan ge en bild av vilka klasser som är mest speciella. Ett enkelt sätt att göra det på är att spara utfallet av <code>chisq.test()</code> som ett objekt och därifrån hämta <code>observed</code> och <code>expected</code>. Som fortsättning på fotbollsexemplet:</p>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb214-1"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb214-1" tabindex="-1"></a>test <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(<span class="fu">c</span>(<span class="dv">947</span>, <span class="dv">518</span>, <span class="dv">1285</span>), <span class="at">p =</span> <span class="fu">c</span>(<span class="fl">0.33</span>, <span class="fl">0.2</span>, <span class="fl">0.47</span>))</span>
<span id="cb214-2"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb214-2" tabindex="-1"></a>test<span class="sc">$</span>expected</span></code></pre></div>
<pre><code>## [1]  907.5  550.0 1292.5</code></pre>
<div class="sourceCode" id="cb216"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb216-1"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb216-1" tabindex="-1"></a>test<span class="sc">$</span>observed</span></code></pre></div>
<pre><code>## [1]  947  518 1285</code></pre>
<div class="sourceCode" id="cb218"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb218-1"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb218-1" tabindex="-1"></a>(test<span class="sc">$</span>observed <span class="sc">-</span> test<span class="sc">$</span>expected)<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> test<span class="sc">$</span>expected</span></code></pre></div>
<pre><code>## [1] 1.71928375 1.86181818 0.04352031</code></pre>
<p>Antalet hemmavinster (det tredje värdet) ligger när den teoretiska sannolikheten medan de övriga två utfallen ligger längre från.</p>
<div class="exercise">
<p><span id="exr:unlabeled-div-84" class="exercise"><strong>Uppgift 4.17  (Udda färger) </strong></span>Spara testobjektet från testet på M&amp;M-färger för att se vilka färger som avviker mest från det väntade utfallet.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-85" class="exercise"><strong>Uppgift 4.18  (Fågelproportioner som chi-två) </strong></span>I naturreservatet från en tidigare uppgift tror man fördelningen av tre fåglar (tärnmås, fiskmås och fisktärna) är 50, 30 respektive 20 procent. En studie ger antalen 115, 54 respektive 31. Genomför ett chi-två-test för att testa de antagna andelarna. Är resultatet i linje med de separata testen från den tidigare uppgiften?</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-86" class="exercise"><strong>Uppgift 4.19  (Udda fåglar) </strong></span>Spara testobjektet från chi-två-testet för fåglarna för att se vilka fågelarter som avviker mest från det väntade utfallet.</p>
</div>
</div>
<div id="chi-två-test-när-någon-parameter-skattas-från-datan" class="section level2 hasAnchor" number="4.5">
<h2><span class="header-section-number">4.5</span> Chi-två-test när någon parameter skattas från datan<a href="ett-stickprov-av-icke-normalfördelad-data.html#chi-två-test-när-någon-parameter-skattas-från-datan" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>(Det här stycket är överkurs och kan läsas översiktligt eller hoppas över.)</p>
<p>I de exempel vi sett hittills har nollhypotesen direkt givit de sannolikheter vi vill testa. Ett annat vanligt fall är att man testar om värdena följer en viss fördelning, men parametervärden i den fördelningen skattas från den insamlade datan. Ta som exempel frågan om antal mål per match följer en poissonfördelning. Hypoteserna ges av</p>
<p>H0: antal mål följer en poissonfördelning,</p>
<p>H1: antal mål följer ej en poissonfördelning.</p>
<p>Här måste vi skatta medelvärdet från datan för att beräkna sannolikheter från fördelningen.</p>
<div class="sourceCode" id="cb220"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb220-1"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb220-1" tabindex="-1"></a>mean_goals <span class="ot">&lt;-</span> <span class="fu">mean</span>(dat_alls<span class="sc">$</span>hemmamal <span class="sc">+</span> dat_alls<span class="sc">$</span>bortamal)</span>
<span id="cb220-2"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb220-2" tabindex="-1"></a>mean_goals</span></code></pre></div>
<pre><code>## [1] 3.290182</code></pre>
<div class="sourceCode" id="cb222"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb222-1"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb222-1" tabindex="-1"></a>dat_goals <span class="ot">&lt;-</span> dat_alls <span class="sc">%&gt;%</span> </span>
<span id="cb222-2"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb222-2" tabindex="-1"></a>  <span class="fu">count</span>(Mål <span class="ot">=</span> bortamal <span class="sc">+</span> hemmamal, <span class="at">name =</span> <span class="st">&quot;O&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb222-3"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb222-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">p =</span> <span class="fu">dpois</span>(Mål, <span class="at">lambda =</span> mean_goals),</span>
<span id="cb222-4"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb222-4" tabindex="-1"></a>         <span class="at">E =</span> p <span class="sc">*</span> <span class="dv">2750</span>)</span>
<span id="cb222-5"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb222-5" tabindex="-1"></a>dat_goals</span></code></pre></div>
<pre><code>## # A tibble: 13 × 4
##      Mål     O        p       E
##    &lt;dbl&gt; &lt;int&gt;    &lt;dbl&gt;   &lt;dbl&gt;
##  1     0   138 0.0372   102.   
##  2     1   383 0.123    337.   
##  3     2   548 0.202    554.   
##  4     3   542 0.221    608.   
##  5     4   466 0.182    500.   
##  6     5   306 0.120    329.   
##  7     6   183 0.0656   180.   
##  8     7    97 0.0308    84.8  
##  9     8    42 0.0127    34.9  
## 10     9    29 0.00464   12.8  
## 11    10     6 0.00153    4.20 
## 12    11     5 0.000456   1.26 
## 13    12     5 0.000125   0.344</code></pre>
<p>En graf kan illustrera faktiska antal (som punkter) och den skattade poissonfördelningen (som linje).</p>
<div class="exercise">
<p><span id="exr:unlabeled-div-87" class="exercise"><strong>Uppgift 4.20  (Målgraf) </strong></span>Fyll i de saknade delarna i koden nedan för en graf med faktiska antal <code>O</code> som punkter och förväntade antal <code>E</code> som en linje.</p>
<div class="sourceCode" id="cb224"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb224-1"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb224-1" tabindex="-1"></a><span class="fu">ggplot</span>(dat_goals) <span class="sc">+</span></span>
<span id="cb224-2"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb224-2" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> Mål, <span class="at">y =</span> ___)) <span class="sc">+</span></span>
<span id="cb224-3"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb224-3" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> Mål, <span class="at">y =</span> ___))</span></code></pre></div>
</div>
<p>De faktiska observationerna är inte så långt från poissonfördelningen.</p>
<p>Ett problem med de förväntade antalen är att några av dem är under 5 - den gräns vi satte för en acceptabel chi-två-approximation. Det vanligaste sättet att hantera det är att slå ihop klasser. Här slås klasser över 9 ihop till en grupp. Det är inte så väsentligt hur det görs här, även om <code>ifelse()</code> kan vara ett nyttigt trick.</p>
<div class="sourceCode" id="cb225"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb225-1"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb225-1" tabindex="-1"></a>dat_goals_merged <span class="ot">&lt;-</span> dat_goals <span class="sc">%&gt;%</span> </span>
<span id="cb225-2"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb225-2" tabindex="-1"></a>  <span class="fu">mutate</span>(Mål <span class="ot">=</span> <span class="fu">ifelse</span>(Mål <span class="sc">&gt;</span> <span class="dv">9</span>, <span class="dv">10</span>, Mål)) <span class="sc">%&gt;%</span> </span>
<span id="cb225-3"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb225-3" tabindex="-1"></a>  <span class="fu">group_by</span>(Mål) <span class="sc">%&gt;%</span> </span>
<span id="cb225-4"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb225-4" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">O =</span> <span class="fu">sum</span>(O),</span>
<span id="cb225-5"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb225-5" tabindex="-1"></a>            <span class="at">p =</span> <span class="fu">sum</span>(p),</span>
<span id="cb225-6"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb225-6" tabindex="-1"></a>            <span class="at">E =</span> <span class="fu">sum</span>(E))</span>
<span id="cb225-7"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb225-7" tabindex="-1"></a>dat_goals_merged</span></code></pre></div>
<pre><code>## # A tibble: 11 × 4
##      Mål     O       p      E
##    &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt;  &lt;dbl&gt;
##  1     0   138 0.0372  102.  
##  2     1   383 0.123   337.  
##  3     2   548 0.202   554.  
##  4     3   542 0.221   608.  
##  5     4   466 0.182   500.  
##  6     5   306 0.120   329.  
##  7     6   183 0.0656  180.  
##  8     7    97 0.0308   84.8 
##  9     8    42 0.0127   34.9 
## 10     9    29 0.00464  12.8 
## 11    10    16 0.00211   5.80</code></pre>
<p>En sista svårighet är antalet frihetsgrader. I ett goodness-of-fit-test ges antalet frihetsgrader av antalet klasser minus antalet skattade parametrar minus 1. I det här fallet har vi nu 11 klasser och vi har skattat en parameter. Vi ska alltså ha 9 frihetsgrader i testet. Funktionen <code>chisq.test()</code> beräknar tyvärr antalet frihetsgrader internt som antalet klasser minus 1, så vi får beräkna chi-två-värde och p-värde på egen hand.</p>
<div class="sourceCode" id="cb227"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb227-1"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb227-1" tabindex="-1"></a>chisq_value <span class="ot">&lt;-</span> <span class="fu">sum</span>((dat_goals_merged<span class="sc">$</span>O <span class="sc">-</span> dat_goals_merged<span class="sc">$</span>E)<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> dat_goals_merged<span class="sc">$</span>E)</span>
<span id="cb227-2"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb227-2" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pchisq</span>(chisq_value, <span class="at">df =</span> <span class="dv">9</span>)</span></code></pre></div>
<pre><code>## [1] 6.984746e-12</code></pre>
<p>Chi-två-värdet blir extremt stort och p-värdet väldigt lågt. Nollhypotesen att antalet mål följer en poissonfördelning förkastas.</p>
</div>
<div id="bonus.-interaktiva-kartor-med-leaflet" class="section level2 hasAnchor" number="4.6">
<h2><span class="header-section-number">4.6</span> Bonus. Interaktiva kartor med leaflet<a href="ett-stickprov-av-icke-normalfördelad-data.html#bonus.-interaktiva-kartor-med-leaflet" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Paketet <code>leaflet</code> (<a href="https://rstudio.github.io/leaflet/" class="uri">https://rstudio.github.io/leaflet/</a>) kopplar R till leaflet - ett verktyg för interaktiva kartor som ofta använd för kartor online.</p>
<div class="exercise">
<p><span id="exr:unlabeled-div-88" class="exercise"><strong>Uppgift 4.21  (Installera leaflet) </strong></span>Installera och ladda `leaflet genom att fylla i och köra raden nedan.</p>
<div class="sourceCode" id="cb229"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb229-1"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb229-1" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;leaflet&quot;</span>)</span>
<span id="cb229-2"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb229-2" tabindex="-1"></a><span class="fu">library</span>(leaflet)</span></code></pre></div>
</div>
<p>Som en första kontroll kan vi köra den exempelkod som ges på hemsidan länkad till ovan.</p>
<div class="sourceCode" id="cb230"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb230-1"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb230-1" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">leaflet</span>() <span class="sc">%&gt;%</span></span>
<span id="cb230-2"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb230-2" tabindex="-1"></a>  <span class="fu">addTiles</span>() <span class="sc">%&gt;%</span></span>
<span id="cb230-3"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb230-3" tabindex="-1"></a>  <span class="fu">addMarkers</span>(<span class="at">lng =</span> <span class="fl">174.768</span>, <span class="at">lat =</span> <span class="sc">-</span><span class="fl">36.852</span>, <span class="at">popup=</span><span class="st">&quot;The birthplace of R&quot;</span>)</span>
<span id="cb230-4"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb230-4" tabindex="-1"></a>m</span></code></pre></div>
<p>På canvassidan finns en excelfil med data tillgänglig på Artportalen - <em>Artportalen, feromoninventering, 2011-2013.xlsx</em>. Datan kommer från från ett inventeringsprojekt vid SLU.</p>
<div class="exercise">
<p><span id="exr:unlabeled-div-89" class="exercise"><strong>Uppgift 4.22  (Importera datan) </strong></span>Ladda ner excelfilen och läs in datan med <code>read_excel()</code> från paketet <code>readxl</code>.</p>
<div class="sourceCode" id="cb231"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb231-1"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb231-1" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb231-2"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb231-2" tabindex="-1"></a>dat_leaf <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">&quot;___&quot;</span>)</span></code></pre></div>
</div>
<p>Kartans utseende kan ändras genom att ange en källa och karttyp. Tillgängliga alternativ kan skrivas ut med <code>providers</code>.</p>
<div class="sourceCode" id="cb232"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb232-1"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb232-1" tabindex="-1"></a><span class="fu">leaflet</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb232-2"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb232-2" tabindex="-1"></a>  <span class="fu">addTiles</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb232-3"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb232-3" tabindex="-1"></a>  <span class="fu">addProviderTiles</span>(providers<span class="sc">$</span>Stamen.Toner)</span></code></pre></div>
<div class="exercise">
<p><span id="exr:unlabeled-div-90" class="exercise"><strong>Uppgift 4.23  (Baskarta) </strong></span>Skriv ut tillgängliga baskartor med <code>providers</code>. Välj ett alternativ slumpmässigt och ändra koden ovan för att se hur det ser ut.</p>
</div>
<p>För att lägga till datapunkter kan man använda <code>addCircleMarkers()</code>.</p>
<div class="sourceCode" id="cb233"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb233-1"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb233-1" tabindex="-1"></a><span class="fu">leaflet</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb233-2"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb233-2" tabindex="-1"></a>  <span class="fu">addTiles</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb233-3"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb233-3" tabindex="-1"></a>  <span class="fu">addCircleMarkers</span>(<span class="at">lng =</span> dat_leaf<span class="sc">$</span>lng, <span class="at">lat =</span> dat_leaf<span class="sc">$</span>lat, <span class="at">radius =</span> <span class="dv">10</span>)</span></code></pre></div>
<div class="exercise">
<p><span id="exr:unlabeled-div-91" class="exercise"><strong>Uppgift 4.24  (Cirkelstorlek) </strong></span>Ändra storleken på cirklarna från <code>addCircleMarkers()</code> genom argumentet <code>radius</code>.</p>
</div>
<p>Slutligen kan vi lägga till en etikett för år med argumentet <code>popup</code>. Texten kommer upp när man klickar på en punkt.</p>
<div class="sourceCode" id="cb234"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb234-1"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb234-1" tabindex="-1"></a><span class="fu">leaflet</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb234-2"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb234-2" tabindex="-1"></a>  <span class="fu">addTiles</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb234-3"><a href="ett-stickprov-av-icke-normalfördelad-data.html#cb234-3" tabindex="-1"></a>  <span class="fu">addCircleMarkers</span>(<span class="at">lng =</span> dat_leaf<span class="sc">$</span>lng, <span class="at">lat =</span> dat_leaf<span class="sc">$</span>lat, <span class="at">radius =</span> <span class="dv">10</span>, <span class="at">popup =</span> dat_leaf<span class="sc">$</span>Rödlistade)</span></code></pre></div>
<div class="exercise">
<p><span id="exr:unlabeled-div-92" class="exercise"><strong>Uppgift 4.25  (Artnamn) </strong></span>Ändra i koden ovan för att ange artnamn som popup-text istället för rödlistestatus. Funktionen <code>paste()</code> kan också vara intressant för att ta med mer information i texten: <code>paste(dat_leaf$Rödlistade, dat_leaf$Antal)</code> skulle exempelvis ge både status och antal individer vid den specifika observationen.</p>
</div>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="ett-stickprov-av-normalfördelad-data.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="test-för-två-stickprov.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": false
},
"fontsettings": {
"theme": "white",
"family": "serif",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["R-anvisningar.pdf"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
